/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Default Response */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sesion': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Usuario actual
     * @description Devuelve el usuario autenticado, su empresa activa y sus permisos.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Usuario actualmente autenticado, su empresa activa y sus permisos. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Id del usuario en sesión. */
              id: string;
              /** @description Nombre de inicio de sesión (minúsculas). */
              username: string;
              /** @description Nombre para mostrar del usuario. */
              nombre: string;
              /** @description Empresa activa de la sesión (multi-empresa explícito). */
              empresaActiva: {
                /** @description Id de la empresa activa de la sesión. */
                id: number;
                /** @description Nombre de la empresa activa. */
                nombre: string;
              };
              /** @description Claves de permiso efectivas del usuario (unión de sus roles). */
              permisos: (
                | 'ordenes.modificar'
                | 'ordenes.precio-maquila'
                | 'ordenes.habilitacion'
                | 'ordenes.ver-costos'
                | 'ordenes.ver-precio-real-maquila'
                | 'pedidos.modificar'
                | 'pedidos.modificar-reales'
                | 'clientes.modificar'
                | 'proveedores.modificar'
                | 'maquileros.programar'
                | 'maquileros.alta-asegurados'
                | 'etiquetas.modificar'
                | 'compras.autorizar'
                | 'produccion.corte-salidas'
                | 'produccion.entradas-maquila'
                | 'telas.ver-totales'
                | 'ipt.clasificar-modelos'
                | 'ipt.consultar-existencias'
                | 'ipt.fecha-libre'
                | 'ipt.modificar-movimientos'
                | 'ipt.cantidades-negativas'
                | 'esma.ver-pagos'
                | 'esma.modificar'
                | 'rc.ver-botones'
                | 'rc.fechas-retraso'
                | 'rc.fecha-libre-cumplimiento'
                | 'calidad.generar-auditorias'
                | 'calidad.modificar-auditorias'
                | 'calidad.actualizar-auditorias'
                | 'indicadores.fecha-libre'
                | 'indicadores.ip-productividad'
                | 'indicadores.ip-confiabilidad'
                | 'indicadores.ip-muestrarios'
                | 'indicadores.ciclicos-alta'
                | 'indicadores.ciclicos-conteo'
                | 'indicadores.ciclicos-consulta'
                | 'indicadores.almacen-productividad'
                | 'consultas.ver-importes'
                | 'usuarios.administrar'
                | 'roles.administrar'
                | 'almacenes.ver'
                | 'almacenes.administrar'
                | 'empresas.administrar'
              )[];
            };
          };
        };
        /** @description Respuesta de error de la API. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/almacenes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Listar almacenes */
    get: {
      parameters: {
        query?: {
          /** @description Página (1-based). */
          pagina?: number;
          /** @description Renglones por página (máx 100). */
          porPagina?: number;
          /** @description Texto a buscar en el nombre (insensible a mayúsculas). */
          busqueda?: string;
          /** @description Filtra por tipo de almacén. */
          tipo?: 'PT' | 'TELA' | 'AVIO';
          /** @description Incluye los desactivados ("true"/"false"). */
          incluirInactivos?: string;
          /** @description Lista almacenes de todas las empresas ("true"/"false"). */
          todasLasEmpresas?: string;
          /** @description Columna de ordenamiento. */
          ordenarPor?: 'nombre' | 'tipo' | 'creadoEn';
          /** @description Dirección del orden. */
          direccion?: 'asc' | 'desc';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Página de almacenes. */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Almacenes de la página. */
              datos: {
                /** @description Id del almacén. */
                id: number;
                /** @description Nombre del almacén. */
                nombre: string;
                /**
                 * @description Tipo: PT, TELA o AVIO.
                 * @enum {string}
                 */
                tipo: 'PT' | 'TELA' | 'AVIO';
                /** @description Falso si está desactivado (borrado suave). */
                activo: boolean;
                /** @description Empresa dueña, o null si es un almacén global. */
                idEmpresa: number | null;
                /**
                 * Format: date-time
                 * @description Fecha de alta (ISO 8601).
                 */
                creadoEn: string;
                /** @description Id del usuario que lo creó. */
                creadoPorId: string | null;
                /**
                 * Format: date-time
                 * @description Fecha de la última modificación (ISO 8601).
                 */
                modificadoEn: string;
                /** @description Id del último usuario que lo modificó. */
                modificadoPorId: string | null;
              }[];
              /** @description Total de almacenes que cumplen el filtro. */
              total: number;
              /** @description Página devuelta. */
              pagina: number;
              /** @description Renglones por página. */
              porPagina: number;
              /** @description Total de páginas. */
              totalPaginas: number;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
      };
    };
    put?: never;
    /** Crear un almacén */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            nombre: string;
            /** @enum {string} */
            tipo: 'PT' | 'TELA' | 'AVIO';
            idEmpresa?: number;
          };
        };
      };
      responses: {
        /** @description Almacén del catálogo (base del kardex único). */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Id del almacén. */
              id: number;
              /** @description Nombre del almacén. */
              nombre: string;
              /**
               * @description Tipo: PT, TELA o AVIO.
               * @enum {string}
               */
              tipo: 'PT' | 'TELA' | 'AVIO';
              /** @description Falso si está desactivado (borrado suave). */
              activo: boolean;
              /** @description Empresa dueña, o null si es un almacén global. */
              idEmpresa: number | null;
              /**
               * Format: date-time
               * @description Fecha de alta (ISO 8601).
               */
              creadoEn: string;
              /** @description Id del usuario que lo creó. */
              creadoPorId: string | null;
              /**
               * Format: date-time
               * @description Fecha de la última modificación (ISO 8601).
               */
              modificadoEn: string;
              /** @description Id del último usuario que lo modificó. */
              modificadoPorId: string | null;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/almacenes/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Obtener un almacén */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Id del almacén. */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Almacén del catálogo (base del kardex único). */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Id del almacén. */
              id: number;
              /** @description Nombre del almacén. */
              nombre: string;
              /**
               * @description Tipo: PT, TELA o AVIO.
               * @enum {string}
               */
              tipo: 'PT' | 'TELA' | 'AVIO';
              /** @description Falso si está desactivado (borrado suave). */
              activo: boolean;
              /** @description Empresa dueña, o null si es un almacén global. */
              idEmpresa: number | null;
              /**
               * Format: date-time
               * @description Fecha de alta (ISO 8601).
               */
              creadoEn: string;
              /** @description Id del usuario que lo creó. */
              creadoPorId: string | null;
              /**
               * Format: date-time
               * @description Fecha de la última modificación (ISO 8601).
               */
              modificadoEn: string;
              /** @description Id del último usuario que lo modificó. */
              modificadoPorId: string | null;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Desactivar un almacén (borrado suave) */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Id del almacén. */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Almacén del catálogo (base del kardex único). */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Id del almacén. */
              id: number;
              /** @description Nombre del almacén. */
              nombre: string;
              /**
               * @description Tipo: PT, TELA o AVIO.
               * @enum {string}
               */
              tipo: 'PT' | 'TELA' | 'AVIO';
              /** @description Falso si está desactivado (borrado suave). */
              activo: boolean;
              /** @description Empresa dueña, o null si es un almacén global. */
              idEmpresa: number | null;
              /**
               * Format: date-time
               * @description Fecha de alta (ISO 8601).
               */
              creadoEn: string;
              /** @description Id del usuario que lo creó. */
              creadoPorId: string | null;
              /**
               * Format: date-time
               * @description Fecha de la última modificación (ISO 8601).
               */
              modificadoEn: string;
              /** @description Id del último usuario que lo modificó. */
              modificadoPorId: string | null;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Actualizar un almacén */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Id del almacén. */
          id: number;
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            nombre?: string;
            /** @enum {string} */
            tipo?: 'PT' | 'TELA' | 'AVIO';
            idEmpresa?: number;
            activo?: boolean;
          };
        };
      };
      responses: {
        /** @description Almacén del catálogo (base del kardex único). */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Id del almacén. */
              id: number;
              /** @description Nombre del almacén. */
              nombre: string;
              /**
               * @description Tipo: PT, TELA o AVIO.
               * @enum {string}
               */
              tipo: 'PT' | 'TELA' | 'AVIO';
              /** @description Falso si está desactivado (borrado suave). */
              activo: boolean;
              /** @description Empresa dueña, o null si es un almacén global. */
              idEmpresa: number | null;
              /**
               * Format: date-time
               * @description Fecha de alta (ISO 8601).
               */
              creadoEn: string;
              /** @description Id del usuario que lo creó. */
              creadoPorId: string | null;
              /**
               * Format: date-time
               * @description Fecha de la última modificación (ISO 8601).
               */
              modificadoEn: string;
              /** @description Id del último usuario que lo modificó. */
              modificadoPorId: string | null;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
        /** @description Respuesta de error de la API. */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @description Código estable del error (p. ej. VALIDACION, PERMISO, NO_AUTENTICADO). */
              codigo: string;
              /** @description Mensaje en español, apto para mostrar al usuario. */
              mensaje: string;
              /** @description Detalle estructurado opcional (p. ej. errores por campo). */
              detalles?: unknown;
            };
          };
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
