/**
 * Contrato — lo compartido entre front y back (plan maestro §3): catálogo
 * tipado de permisos (A4) y esquemas Zod de entrada (una sola definición de
 * reglas de captura para UI y servidor). Es la fuente del OpenAPI que se genera
 * en E3 y desde el que el frontend deriva su cliente tipado.
 */
export {
  CATALOGO_PERMISOS,
  CLAVES_PERMISO,
  MODULOS_PERMISO,
  esClavePermiso,
  permisosPorModulo,
  type ClavePermiso,
  type DefinicionPermiso,
  type ModuloPermiso,
  type OrigenAcceso,
} from './permisos.js';

export { esquemaLogin, type DatosLogin } from './esquemas/login.js';

export {
  ETIQUETAS_TIPO_ALMACEN,
  TIPOS_ALMACEN,
  esquemaAlmacenCrear,
  esquemaAlmacenEditar,
  esquemaAlmacenSalida,
  esquemaAlmacenesQuery,
  esquemaAlmacenesPagina,
  type DatosAlmacenCrear,
  type DatosAlmacenEditar,
  type AlmacenSalida,
  type AlmacenesQuery,
  type AlmacenesPagina,
  type TipoAlmacenClave,
} from './esquemas/almacen.js';

export {
  esquemaUsuarioCrear,
  esquemaUsuarioEditar,
  esquemaUsuarioAsignarRoles,
  esquemaUsuarioCambiarContrasena,
  esquemaUsuarioSalida,
  esquemaUsuariosQuery,
  esquemaUsuariosPagina,
  type DatosUsuarioCrear,
  type DatosUsuarioEditar,
  type DatosUsuarioAsignarRoles,
  type DatosUsuarioCambiarContrasena,
  type UsuarioSalida,
  type UsuariosQuery,
  type UsuariosPagina,
} from './esquemas/usuario.js';

export {
  esquemaEmpresaCrear,
  esquemaEmpresaEditar,
  esquemaEmpresaSalida,
  esquemaConfiguracionEmpresaActualizar,
  esquemaConfiguracionEmpresaSalida,
  esquemaEmpresaLogoCrear,
  esquemaEmpresaLogoConfirmar,
  esquemaEmpresaLogoSubida,
  esquemaEmpresaLogoSalida,
  type DatosEmpresaCrear,
  type DatosEmpresaEditar,
  type EmpresaSalida,
  type DatosConfiguracionEmpresaActualizar,
  type ConfiguracionEmpresaSalida,
  type DatosEmpresaLogoCrear,
  type DatosEmpresaLogoConfirmar,
  type EmpresaLogoSubida,
  type EmpresaLogoSalida,
} from './esquemas/empresa.js';

export {
  esquemaRolSalida,
  esquemaCrearRolBody,
  esquemaActualizarRolBody,
  esquemaAsignarPermisosBody,
  esquemaPermisoCatalogoSalida,
  esquemaModuloPermisosSalida,
  esquemaCatalogoPermisosSalida,
  type RolSalida,
  type CrearRolBody,
  type ActualizarRolBody,
  type AsignarPermisosBody,
  type PermisoCatalogoSalida,
  type ModuloPermisosSalida,
  type CatalogoPermisosSalida,
} from './esquemas/rol.js';

// ── Catálogos (F1-E1): maestros globales (ADR-0007) ──────────────────────────
export {
  TIPOS_ARCHIVO_PROVEEDOR,
  ETIQUETAS_TIPO_ARCHIVO_PROVEEDOR,
  esquemaProveedorCrear,
  esquemaProveedorEditar,
  esquemaProveedorPatchCuerpo,
  esquemaProveedorSalida,
  esquemaProveedoresQuery,
  esquemaProveedoresPagina,
  esquemaRolProveedorSalida,
  esquemaProveedorAdjuntoCrear,
  esquemaProveedorAdjuntoSubida,
  esquemaProveedorAdjuntoSalida,
  esquemaProveedorAdjuntosLista,
  esquemaProveedorAvioSalida,
  esquemaProveedorAviosLista,
  esquemaProveedorAvioAsignar,
  esquemaProveedorContactoCrear,
  esquemaProveedorContactoEditarCuerpo,
  esquemaProveedorContactoSalida,
  esquemaAnalizarConstanciaCuerpo,
  esquemaAnalizarConstanciaSalida,
  esquemaRegimenPropuesto,
  type DatosProveedorCrear,
  type DatosProveedorEditar,
  type DatosProveedorPatchCuerpo,
  type ProveedorSalida,
  type ProveedoresQuery,
  type ProveedoresPagina,
  type TipoArchivoProveedorClave,
  type RolProveedorSalida,
  type DatosProveedorAdjuntoCrear,
  type ProveedorAdjuntoSubida,
  type ProveedorAdjuntoSalida,
  type ProveedorAdjuntosLista,
  type ProveedorAvioSalida,
  type ProveedorAviosLista,
  type DatosProveedorAvioAsignar,
  type DatosProveedorContactoCrear,
  type DatosProveedorContactoEditarCuerpo,
  type ProveedorContactoSalida,
  type DatosAnalizarConstanciaCuerpo,
  type AnalizarConstanciaSalida,
} from './esquemas/proveedor.js';

export {
  MONEDAS,
  METODOS_PAGO,
  esRfcValido,
  esClabeValida,
  type Moneda,
  type MetodoPago,
} from './esquemas/fiscal.js';

export {
  esquemaTemporadaCrear,
  esquemaTemporadaEditar,
  esquemaTemporadaSalida,
  esquemaTemporadasQuery,
  esquemaTemporadasPagina,
  type DatosTemporadaCrear,
  type DatosTemporadaEditar,
  type TemporadaSalida,
  type TemporadasQuery,
  type TemporadasPagina,
} from './esquemas/temporada.js';

export {
  esquemaDireccionEntregaCrear,
  esquemaDireccionEntregaEditar,
  esquemaDireccionEntregaSalida,
  esquemaDireccionesEntregaQuery,
  esquemaDireccionesEntregaPagina,
  type DatosDireccionEntregaCrear,
  type DatosDireccionEntregaEditar,
  type DireccionEntregaSalida,
  type DireccionesEntregaQuery,
  type DireccionesEntregaPagina,
} from './esquemas/direccion-entrega.js';

export {
  esquemaEtiquetaMarcaCrear,
  esquemaEtiquetaMarcaEditar,
  esquemaEtiquetaMarcaSalida,
  esquemaEtiquetasMarcaQuery,
  esquemaEtiquetasMarcaPagina,
  type DatosEtiquetaMarcaCrear,
  type DatosEtiquetaMarcaEditar,
  type EtiquetaMarcaSalida,
  type EtiquetasMarcaQuery,
  type EtiquetasMarcaPagina,
} from './esquemas/etiqueta-marca.js';

export {
  esquemaColorCrear,
  esquemaColorEditar,
  esquemaColorSalida,
  esquemaColorFusionadoEn,
  esquemaColoresQuery,
  esquemaColoresPagina,
  esquemaColorFusionar,
  type DatosColorCrear,
  type DatosColorEditar,
  type ColorSalida,
  type ColorFusionadoEn,
  type ColoresQuery,
  type ColoresPagina,
  type DatosColorFusionar,
} from './esquemas/color.js';

// ── Catálogos estructurados (F1-E2): maestros globales con relaciones (ADR-0007) ──
// NOTA (fusión de terceros, D12/R15): maquileros se eliminó como catálogo (un maquilero
// es ahora un Proveedor con sus roles de servicio).
export {
  esquemaTallaCrear,
  esquemaTallaEditar,
  esquemaTallaSalida,
  esquemaListarTallas,
  esquemaTallasPagina,
  esquemaCurvaCrear,
  esquemaCurvaEditar,
  esquemaCurvaSalida,
  esquemaCurvaTallaItemSalida,
  esquemaListarCurvas,
  esquemaCurvasPagina,
  type DatosTallaCrear,
  type DatosTallaEditar,
  type TallaSalida,
  type ListarTallas,
  type TallasPagina,
  type DatosCurvaCrear,
  type DatosCurvaEditar,
  type CurvaSalida,
  type CurvaTallaItemSalida,
  type ListarCurvas,
  type CurvasPagina,
} from './esquemas/talla.js';

export {
  TIPOS_CAMPO_CLIENTE,
  esquemaClienteCrear,
  esquemaClienteEditar,
  esquemaClienteSalida,
  esquemaListarClientes,
  esquemaClientesPagina,
  esquemaClienteCampoCrear,
  esquemaClienteCampoEditar,
  esquemaClienteCampoSalida,
  type TipoCampoClienteClave,
  type DatosClienteCrear,
  type DatosClienteEditar,
  type ClienteSalida,
  type ListarClientes,
  type ClientesPagina,
  type DatosClienteCampoCrear,
  type DatosClienteCampoEditar,
  type ClienteCampoSalida,
  // ⭐ V1-E8y (§Post-F9.152) — contactos del cliente (la compradora), con departamento OPCIONAL.
  esquemaClienteContactoCrear,
  esquemaClienteContactoEditarCuerpo,
  esquemaClienteContactoSalida,
  esquemaClienteContactosLista,
  esquemaClienteContactosQuery,
  type DatosClienteContactoCrear,
  type DatosClienteContactoEditarCuerpo,
  type ClienteContactoSalida,
} from './esquemas/cliente.js';

// ── Catálogos de materiales (F1-E3): globales con relaciones (ADR-0007/ADR-0009) ──
export {
  TIPOS_COMPONENTE_TELA,
  esquemaTelaCrear,
  // (esquemaTelaCrearMigracion NO se reexporta: es SOLO del ETL; el dominio lo importa directo)
  esquemaTelaEditar,
  esquemaTelaSalida,
  esquemaListarTelas,
  esquemaTelasPagina,
  esquemaTelaColorSalida,
  esquemaTelaColoresLista,
  esquemaTelaCategoriaCrear,
  esquemaTelaCategoriaEditar,
  esquemaTelaCategoriaSalida,
  esquemaTelasCategoriasQuery,
  esquemaTelasCategoriasPagina,
  esquemaComposicionTelaCrear,
  esquemaComposicionTelaEditar,
  esquemaComposicionTelaSalida,
  esquemaComposicionesTelaQuery,
  esquemaComposicionesTelaPagina,
  ETIQUETA_UNIDAD_TELA,
  type TipoComponenteTelaClave,
  type DatosTelaCrear,
  type DatosTelaEditar,
  type TelaSalida,
  type ListarTelas,
  type TelasPagina,
  type TelaColorSalida,
  type TelaColoresLista,
  type DatosTelaCategoriaCrear,
  type DatosTelaCategoriaEditar,
  type TelaCategoriaSalida,
  type TelasCategoriasQuery,
  type TelasCategoriasPagina,
  type DatosComposicionTelaCrear,
  type DatosComposicionTelaEditar,
  type ComposicionTelaSalida,
  type ComposicionesTelaQuery,
  type ComposicionesTelaPagina,
} from './esquemas/tela.js';

export {
  esquemaAvioCrear,
  esquemaAvioEditar,
  esquemaAvioPatchCuerpo,
  esquemaAvioSalida,
  esquemaListarAvios,
  esquemaAviosPagina,
  esquemaAvioProveedorSalida,
  esquemaAvioProveedoresLista,
  type DatosAvioCrear,
  type DatosAvioEditar,
  type DatosAvioPatchCuerpo,
  type AvioSalida,
  type ListarAvios,
  type AviosPagina,
  type AvioProveedorSalida,
  type AvioProveedoresLista,
} from './esquemas/avio.js';

// ── Arte del modelo (V1-E3d §Post-F9.35 + V1-E3f §Post-F9.52/.58): vive en el modelo,
//    su tipo sale del catálogo ÚNICO (`TipoProceso.esArte`) y sus fotos son PLURALES ──
export {
  esquemaArteCrear,
  esquemaArteEditar,
  esquemaArtePatchCuerpo,
  esquemaArteFotoResumen,
  esquemaArteSalida,
  esquemaArtesLista,
  esquemaArteCopiarCuerpo,
  esquemaGaleriaArteQuery,
  esquemaGaleriaArteItem,
  esquemaGaleriaArtePagina,
  esquemaArteFotoCrear,
  esquemaArteFotoSubida,
  esquemaArteFotoSalida,
  esquemaArteFotosLista,
  type DatosArteCrear,
  type DatosArteEditar,
  type DatosArtePatchCuerpo,
  type ArteSalida,
  type ArtesLista,
  type DatosArteCopiar,
  type GaleriaArteQuery,
  type GaleriaArtePagina,
  type DatosArteFotoCrear,
  type ArteFotoSubida,
  type ArteFotoSalida,
  type ArteFotosLista,
} from './esquemas/arte.js';

// ── Modelos (Módulo 2, F1-E4): catálogo + receta/BOM + fotos (ADR-0007) ──────
export {
  TIPOS_FOTO_MODELO,
  ETIQUETAS_TIPO_FOTO_MODELO,
  esquemaGeneroSalida,
  esquemaModeloCrear,
  esquemaModeloCrearMigracion,
  esquemaModeloEditar,
  esquemaModeloPatchCuerpo,
  esquemaModeloSalida,
  esquemaOrigenModelo,
  esquemaFiltroOrigenModelo,
  esquemaSerieProduccion,
  esquemaPropuestaProduccion,
  esquemaPasarAProduccionCuerpo,
  esquemaPasarAProduccionSalida,
  esquemaEstadoRevisionModelo,
  esquemaRevisionAprobarCuerpo,
  esquemaRevisionRechazarCuerpo,
  esquemaRevisionModeloSalida,
  // ⭐ V1-E8r (§Post-F9.140) — la BANDEJA «Recetas por revisar»: la cola de la revisión de V1-E7d.
  esquemaRecetaPorRevisar,
  esquemaRecetasPorRevisarQuery,
  esquemaRecetasPorRevisarDominio,
  esquemaRecetasPorRevisarPagina,
  esquemaModeloFichaSalida,
  esquemaModelosQuery,
  esquemaModelosPagina,
  esquemaModeloTelaEntrada,
  esquemaModeloAvioEntrada,
  esquemaModeloTelaSalida,
  esquemaModeloAvioSalida,
  esquemaModeloBomTelasCuerpo,
  esquemaModeloBomAviosCuerpo,
  esquemaModeloBomTelasLista,
  esquemaModeloBomAviosLista,
  esquemaModeloCopiarBomCuerpo,
  esquemaModeloFotoCrear,
  esquemaModeloFotoSubida,
  esquemaModeloFotoSalida,
  esquemaModeloFotosLista,
  esquemaModeloFotoEditarCuerpo,
  type TipoFotoModeloClave,
  type GeneroSalida,
  type DatosModeloCrear,
  type DatosModeloCrearMigracion,
  type DatosModeloEditar,
  type DatosModeloPatchCuerpo,
  type ModeloSalida,
  type OrigenModeloClave,
  type EstadoRevisionModeloClave,
  type DatosRevisionAprobar,
  type DatosRevisionRechazar,
  type RevisionModeloSalidaContrato,
  type RecetaPorRevisar,
  type FiltrosRecetasPorRevisar,
  type RecetasPorRevisarPagina,
  type FiltroOrigenModeloClave,
  type PropuestaProduccionSalida,
  type DatosPasarAProduccion,
  type PasarAProduccionSalida,
  type ModeloFichaSalida,
  type ModelosQuery,
  type ModelosPagina,
  type DatosModeloTelaEntrada,
  type DatosModeloAvioEntrada,
  type DatosModeloBomTelas,
  type DatosModeloBomAvios,
  type ModeloBomTelasLista,
  type ModeloBomAviosLista,
  type DatosModeloCopiarBom,
  type DatosModeloFotoCrear,
  type ModeloFotoSubida,
  type ModeloFotoSalida,
  type ModeloFotosLista,
  type DatosModeloFotoEditar,
} from './esquemas/modelo.js';

// ── Curva jalada de las órdenes (V1-E3r, §Post-F9.81 punto 3) ──
export {
  esquemaCurvaSugerida,
  esquemaCurvasSugeridas,
  esquemaAsignarCurvaDesdeOrdenes,
  esquemaCurvaAsignada,
  type DatosAsignarCurvaDesdeOrdenes,
} from './esquemas/curva-sugerida.js';

// ── Pedidos (Módulo PEDIDOS, F2-E1): pedido interno + pedido real (doc 02-Pedidos) ──
export {
  esquemaPedidoLineaEntrada,
  esquemaPedidoCrear,
  esquemaPedidoEditar,
  esquemaPedidoPatchCuerpo,
  esquemaPedidoCancelarCuerpo,
  esquemaPedidoCopiarCuerpo,
  esquemaPedidoLineaSalida,
  esquemaPedidoSalida,
  esquemaListarPedidos,
  esquemaPedidosPagina,
  esquemaPedidoRealCancelarCuerpo,
  esquemaPedidoRealCrear,
  esquemaPedidoRealEditar,
  esquemaPedidoRealLineaSeguimiento,
  esquemaPedidoRealSeguimientoCuerpo,
  esquemaPedidoRealLineaSalida,
  esquemaPedidoRealSalida,
  esquemaPedidoRealesLista,
  type DatosPedidoLineaEntrada,
  type DatosPedidoCrear,
  type DatosPedidoEditar,
  type DatosPedidoPatchCuerpo,
  type DatosPedidoCancelar,
  type DatosPedidoCopiar,
  type PedidoLineaSalida,
  type PedidoSalida,
  type ListarPedidos,
  type PedidosPagina,
  type DatosPedidoRealCancelar,
  type DatosPedidoRealCrear,
  type DatosPedidoRealEditar,
  type DatosPedidoRealLineaSeguimiento,
  type DatosPedidoRealSeguimiento,
  type PedidoRealLineaSalida,
  type PedidoRealSalida,
  type PedidoRealesLista,
} from './esquemas/pedido.js';

// ── Adjuntos del pedido interno (rediseño R3, B3) ──
export {
  esquemaPedidoAdjuntoCrear,
  esquemaPedidoAdjuntoSubida,
  esquemaPedidoAdjuntoSalida,
  esquemaPedidoAdjuntosLista,
  type DatosPedidoAdjuntoCrear,
  type PedidoAdjuntoSubida,
  type PedidoAdjuntoSalida,
  type PedidoAdjuntosLista,
} from './esquemas/adjunto-pedido.js';

// ── Salida a producción + candidatos de desarrollo (rediseño R3, B4/B6) ──
export {
  esquemaSalidaProduccionCuerpo,
  esquemaSalidaProduccionSalida,
  esquemaCandidatosDesarrolloQuery,
  esquemaCandidatoDesarrollo,
  esquemaCandidatosDesarrolloSalida,
  type DatosSalidaProduccion,
  type SalidaProduccionSalida,
  type CandidatosDesarrolloQuery,
  type CandidatoDesarrollo,
  type CandidatosDesarrolloSalida,
} from './esquemas/salida-produccion.js';

// ── Importador del pedido del cliente (rediseño R8, B15 — proto §4.1 "Etapa 3") ──
export {
  esquemaRolColumnaImportacion,
  esquemaMapeoColumna,
  esquemaMapeoImportacion,
  esquemaPlantillaImportacionSalida,
  esquemaPlantillaImportacionVigente,
  esquemaPlantillaImportacionGuardar,
  esquemaAnalizarImportacionCuerpo,
  esquemaGrupoImportacion,
  esquemaPreviewImportacion,
  esquemaAnalizarImportacionSalida,
  esquemaResolucionImportacion,
  esquemaConfirmarImportacionCuerpo,
  esquemaOrdenImportada,
  esquemaConfirmarImportacionSalida,
  esquemaFormatoImportacion,
  esquemaCampoPdfCya,
  esquemaCampoVariableImportacion,
  esquemaPorcentajeAdicional,
  type RolColumnaImportacion,
  type MapeoColumna,
  type MapeoImportacion,
  type PlantillaImportacionSalida,
  type PlantillaImportacionVigente,
  type DatosPlantillaImportacionGuardar,
  type DatosAnalizarImportacion,
  type GrupoImportacion,
  type PreviewImportacion,
  type AnalizarImportacionSalida,
  type DatosResolucionImportacion,
  type DatosConfirmarImportacion,
  type OrdenImportada,
  type ConfirmarImportacionSalida,
  type FormatoImportacion,
  type CampoPdfCya,
  type CampoVariableImportacion,
} from './esquemas/importacion-pedido.js';

// ── Importador de OC del cliente por PDF (petición Daniel — plantilla C&A) ──
export {
  esquemaArchivoPdf,
  esquemaAjusteTallaPdf,
  esquemaArchivoPdfConfirmar,
  esquemaAnalizarPdfCyaCuerpo,
  esquemaTallaPdfCya,
  esquemaCeldaSobrepedido,
  esquemaGrupoSobrepedido,
  esquemaAdvertenciaPdf,
  esquemaOcYaImportada,
  esquemaRenglonPdfPreview,
  esquemaAnalizarPdfCyaSalida,
  esquemaLigaModeloPdf,
  esquemaConfirmarPdfCyaCuerpo,
  esquemaOrdenPdfImportada,
  esquemaPdfNoReconocido,
  esquemaConfirmarPdfCyaSalida,
  MAX_ARCHIVOS_PDF,
  type ArchivoPdf,
  type ArchivoPdfConfirmar,
  type DatosAnalizarPdfCya,
  type TallaPdfCya,
  type CeldaSobrepedido,
  type GrupoSobrepedido,
  type AdvertenciaPdf,
  type OcYaImportada,
  type RenglonPdfPreview,
  type AnalizarPdfCyaSalida,
  type DatosLigaModeloPdf,
  type DatosConfirmarPdfCya,
  type OrdenPdfImportada,
  type PdfNoReconocido,
  type ConfirmarPdfCyaSalida,
} from './esquemas/importacion-pdf.js';

// ── Consulta de pedidos por mes (rediseño R3, B6 — proto §4.1) ──
export {
  esquemaPedidosPorMesQuery,
  esquemaEstatusPedidoMes,
  esquemaPedidoMesRenglon,
  esquemaPedidoMesFila,
  esquemaPedidosPorMesTotales,
  esquemaPedidosPorMesSalida,
  type PedidosPorMesQuery,
  type PedidoMesRenglon,
  type PedidoMesFila,
  type PedidosPorMesTotales,
  type PedidosPorMesSalida,
} from './esquemas/pedidos-mes.js';

// ── Órdenes de producción (Módulo ÓRDENES, F2-E2; doc 03-Produccion) ──────────
export {
  esquemaOrdenTallaEntrada,
  esquemaOrdenLineaEntrada,
  esquemaOrdenCrear,
  esquemaOrdenEditar,
  esquemaOrdenPatchCuerpo,
  esquemaOrdenMatrizCuerpo,
  esquemaOrdenCopiarMatrizCuerpo,
  esquemaOrdenCancelarCuerpo,
  esquemaOrdenReferenciaEntrada,
  esquemaOrdenReferenciasCuerpo,
  esquemaOrdenComentarioCuerpo,
  esquemaEstadoOrden,
  esquemaRequisitosOrden,
  esquemaOrdenTallaSalida,
  esquemaOrdenLineaSalida,
  esquemaOrdenReferenciaSalida,
  esquemaOrdenComentarioSalida,
  esquemaOrdenSalida,
  esquemaListarOrdenes,
  esquemaOrdenesPagina,
  esquemaOrdenesImpresoCuerpo,
  type DatosOrdenTallaEntrada,
  type DatosOrdenLineaEntrada,
  type DatosOrdenCrear,
  type DatosOrdenEditar,
  type DatosOrdenPatchCuerpo,
  type DatosOrdenMatriz,
  type DatosOrdenCopiarMatriz,
  type DatosOrdenCancelar,
  type DatosOrdenReferenciaEntrada,
  type DatosOrdenReferencias,
  type DatosOrdenComentario,
  type RequisitosOrdenSalida,
  type OrdenTallaSalida,
  type OrdenLineaSalida,
  type OrdenReferenciaSalida,
  type OrdenComentarioSalida,
  type OrdenSalida,
  type ListarOrdenes,
  type OrdenesPagina,
  type DatosOrdenesImpreso,
} from './esquemas/orden.js';

// ── Consultas/tableros/búsqueda de Órdenes (Módulo ÓRDENES, F2-E4; doc 03-Produccion) ──
export {
  esquemaOrdenLigeraSalida,
  esquemaOrdenesLigerasPagina,
  esquemaConsultaOrdenes,
  esquemaSemaforoOrden,
  esquemaOrdenIncompletaSalida,
  esquemaOrdenesIncompletasPagina,
  esquemaIncompletasQuery,
  esquemaTableroPedidosMesFila,
  esquemaTableroPedidosMes,
  esquemaTableroPedidosMesQuery,
  esquemaOrdenHitSalida,
  esquemaOrdenesBuscarSalida,
  esquemaOrdenesBuscarQuery,
  type OrdenLigeraSalida,
  type OrdenesLigerasPagina,
  type ConsultaOrdenes,
  type SemaforoOrden,
  type OrdenIncompletaSalida,
  type OrdenesIncompletasPagina,
  type IncompletasQuery,
  type TableroPedidosMesFila,
  type TableroPedidosMes,
  type TableroPedidosMesQuery,
  type OrdenHitSalida,
  type OrdenesBuscarSalida,
  type OrdenesBuscarQuery,
} from './esquemas/orden-consulta.js';

// ── Precios de la orden con rastro inmutable (rediseño R2, §4.4.3; brecha B1) ──
export {
  esquemaCampoPrecioOrden,
  esquemaOrdenPreciosPatchCuerpo,
  esquemaOrdenPrecioUltimoEvento,
  esquemaOrdenPreciosSalida,
  esquemaOrdenPrecioEventoSalida,
  esquemaOrdenPrecioEventosLista,
  type CampoPrecioOrdenApi,
  type DatosOrdenPreciosPatch,
  type OrdenPrecioUltimoEvento,
  type OrdenPreciosSalida,
  type OrdenPrecioEventoSalida,
  type OrdenPrecioEventosLista,
} from './esquemas/orden-precios.js';

// ── Centro de comando de Órdenes (rediseño R2, §4.2; brecha B2) ───────────────
export {
  esquemaOrdenCentroFila,
  esquemaOrdenesCentroPagina,
  esquemaOrdenesCentroQuery,
  type OrdenCentroFila,
  type OrdenesCentroPagina,
  type OrdenesCentroQuery,
} from './esquemas/orden-centro.js';

// ── Órdenes de COMPRA (Módulo 3, F4-E2; doc 03-Produccion §OC) ────────────────
export {
  esquemaCompraLineaTallaEntrada,
  esquemaCompraLineaEntrada,
  esquemaCompraCrear,
  esquemaCompraEditarCuerpo,
  esquemaCompraCancelarCuerpo,
  esquemaCompraDesautorizarCuerpo,
  esquemaEstatusOrdenCompra,
  esquemaCompraLineaTallaSalida,
  esquemaCompraLineaSalida,
  esquemaCompraOrdenLigadaSalida,
  esquemaCompraSalida,
  esquemaListarCompras,
  esquemaComprasPagina,
  esquemaResumenComprasQuery,
  esquemaResumenCompras,
  type DatosCompraLineaTallaEntrada,
  type DatosCompraLineaEntrada,
  type DatosCompraCrear,
  type DatosCompraEditarCuerpo,
  type DatosCompraCancelar,
  type DatosCompraDesautorizar,
  type CompraLineaTallaSalida,
  type CompraLineaSalida,
  type CompraOrdenLigadaSalida,
  type CompraSalida,
  type ListarCompras,
  type ComprasPagina,
  type ResumenComprasQuery,
  type ResumenCompras,
} from './esquemas/compra.js';

// ── Recepción de compras (Módulo 3, F4-E3; doc 03-Produccion §OC; R7) ─────────
export {
  esquemaRecepcionTelaColorEntrada,
  esquemaRecepcionLineaEntrada,
  esquemaRecepcionCrear,
  esquemaRecepcionReversarCuerpo,
  esquemaRecepcionLineaSalida,
  esquemaRecepcionSalida,
  esquemaRecepcionesLista,
  type DatosRecepcionTelaColorEntrada,
  type DatosRecepcionLineaEntrada,
  type DatosRecepcionCrear,
  type DatosRecepcionReversar,
  type RecepcionLineaSalida,
  type RecepcionSalida,
  type RecepcionesLista,
} from './esquemas/recepcion.js';

// ── Notas de salida estructuradas (Módulo 5, F4-E5; doc 03-Produccion §Notas de Salida; R4/R9) ──
export {
  esquemaNotaSalidaLineaEntrada,
  esquemaNotaSalidaCrear,
  esquemaNotaSalidaEditarCuerpo,
  esquemaNotaSalidaCancelarCuerpo,
  esquemaNotaSalidaLineaSalida,
  esquemaNotaSalidaSalida,
  esquemaNotasSalidaQuery,
  esquemaNotasSalidaPagina,
  esquemaResumenNotasQuery,
  esquemaResumenNotasSalida,
  type DatosNotaSalidaLineaEntrada,
  type DatosNotaSalidaCrear,
  type DatosNotaSalidaEditar,
  type DatosNotaSalidaCancelar,
  type NotaSalidaLineaSalida,
  type NotaSalidaSalida,
  type NotasSalidaQuery,
  type NotasSalidaPagina,
  type ResumenNotasQuery,
  type ResumenNotasSalida,
} from './esquemas/nota-salida.js';

// ── Explosión MRP / requerimiento de materiales por orden (Módulo 3, F4-E4; R3/R7) ──
export {
  esquemaEstadoGenerico,
  esquemaDiffRequerimiento,
  esquemaOrigenProveedor,
  esquemaRepartoOrden,
  esquemaRequerimientoSalida,
  esquemaGrupoProveedorSalida,
  esquemaOrdenExplosionada,
  esquemaExplosionSalida,
  esquemaPendienteLiberar,
  esquemaPendienteColor,
  esquemaExplosionCuerpo,
  esquemaOrdenDelPedido,
  esquemaOrdenesDelPedidoSalida,
  esquemaGenerarOcCuerpo,
  esquemaMotivoOmision,
  esquemaOmitidoPlan,
  esquemaPlanLineaOrden,
  esquemaPlanRenglon,
  esquemaPlanProveedor,
  esquemaPlanCompra,
  esquemaOcGeneradaSalida,
  esquemaGenerarOcResultado,
  esquemaAsignarProveedorCuerpo,
  esquemaAsignarProveedorSalida,
  esquemaAsignarProveedorEnBloqueCuerpo,
  esquemaAsignarProveedorEnBloqueSalida,
  esquemaEstatusMaterial,
  esquemaEstatusMaterialFila,
  esquemaEstatusMaterialesSalida,
  // ⭐⭐ V1-E8e (§Post-F9.99) — «con esto queda cubierto» / «volver a pedirlo».
  esquemaDarPorCubiertoCuerpo,
  esquemaDarPorCubiertoSalida,
  type EstadoGenerico,
  type DiffRequerimiento,
  type OrigenProveedor,
  type RepartoOrden,
  type RequerimientoSalida,
  type GrupoProveedorSalida,
  type OrdenExplosionada,
  type ExplosionSalida,
  type PendienteLiberar,
  type PendienteColor,
  type DatosExplosion,
  type OrdenDelPedido,
  type OrdenesDelPedidoSalida,
  type DatosGenerarOc,
  type MotivoOmision,
  type OmitidoPlan,
  type PlanLineaOrden,
  type PlanRenglon,
  type PlanProveedor,
  type DatosDarPorCubierto,
  type DarPorCubiertoSalida,
  type PlanCompra,
  type OcGeneradaSalida,
  type GenerarOcResultado,
  type DatosAsignarProveedor,
  type AsignarProveedorSalida,
  type DatosAsignarProveedorEnBloque,
  type AsignarProveedorEnBloqueSalida,
  type EstatusMaterial,
  type EstatusMaterialFila,
  type EstatusMaterialesSalida,
} from './esquemas/mrp.js';

// ── ⭐⭐ La tela se compra POR COLOR (V1-E3u, §Post-F9.89) ──
export {
  esquemaOrigenPropuestaColor,
  esquemaOpcionColorTela,
  esquemaColorDeLaOrden,
  esquemaTelaConColores,
  esquemaColoresDeTelaSalida,
  esquemaAsignarColorTelaCuerpo,
  esquemaFijarPrecioColorCuerpo,
  esquemaFijarPrecioColorSalida,
  type OrigenPropuestaColor,
  type OpcionColorTela,
  type ColorDeLaOrden,
  type TelaConColores,
  type ColoresDeTelaSalida,
  type DatosAsignarColorTela,
  type DatosFijarPrecioColor,
  type FijarPrecioColorSalida,
} from './esquemas/color-de-la-tela.js';

// ── Habilitación / surtido de avíos por orden (rediseño R6, B13; §4.6) ──
export {
  esquemaEstadoHabilitacion,
  esquemaHabilitacionAvio,
  esquemaHabilitacionOrden,
  type EstadoHabilitacion,
  type HabilitacionAvio,
  type HabilitacionOrden,
} from './esquemas/habilitacion.js';

// ── Receta CONGELADA de la orden (V1-E3d pieza B, §Post-F9.43: "el BOM vive en la OP") ──
export {
  esquemaCambioReceta,
  esquemaDesalineacionReceta,
  esquemaEstadoRenglonReceta,
  esquemaChoqueTraerDelModelo,
  esquemaAbrirRecetaCuerpo,
  esquemaLiberarRecetaCuerpo,
  esquemaMaterialDelModelo,
  esquemaOcComprometida,
  esquemaRecetaAgregarCuerpo,
  esquemaRecetaEditarCuerpo,
  esquemaRecetaOrden,
  esquemaRecetaPorLiberar,
  esquemaRecetasPorLiberarDominio,
  esquemaRecetasPorLiberarPagina,
  esquemaRecetasPorLiberarQuery,
  esquemaReferenciaRenglonReceta,
  esquemaTraerDelModeloCuerpo,
  esquemaTraerDelModeloResultado,
  esquemaRecetaOrdenArte,
  esquemaRecetaOrdenAvio,
  esquemaRecetaOrdenAvioTalla,
  esquemaRecetaOrdenTela,
  esquemaRecetaQuitarCuerpo,
  esquemaRecetaTallaEntrada,
  esquemaRecetaTipoParam,
  esquemaResumenReceta,
  esquemaTipoCambioReceta,
  esquemaTipoRenglonReceta,
  type CambioReceta,
  type ChoqueTraerDelModelo,
  type DatosAbrirReceta,
  type DatosLiberarReceta,
  type DatosTraerDelModelo,
  type FiltrosRecetasPorLiberar,
  type MaterialDelModelo,
  type OcComprometida,
  type RecetaPorLiberar,
  type RecetasPorLiberarPagina,
  type ReferenciaRenglonReceta,
  type TraerDelModeloResultado,
  type DatosRecetaAgregar,
  type DatosRecetaEditar,
  type DatosRecetaQuitar,
  type DesalineacionReceta,
  type EstadoRenglonRecetaClave,
  type RecetaOrden,
  type RecetaOrdenArte,
  type RecetaOrdenAvio,
  type RecetaOrdenAvioTalla,
  type RecetaOrdenTela,
  type ResumenReceta,
  type TipoCambioRecetaClave,
  type TipoRenglonRecetaClave,
} from './esquemas/receta-orden.js';

// ── Producción / WIP + kardex (Módulo 4/6, F3-E1; doc 03-Produccion / 04-Inventarios) ──
export {
  esquemaTipoProcesoCrear,
  esquemaTipoProcesoEditar,
  esquemaTipoProcesoSalida,
  esquemaTiposProcesoQuery,
  esquemaTiposProcesoPagina,
  type DatosTipoProcesoCrear,
  type DatosTipoProcesoEditar,
  type TipoProcesoSalida,
  type TiposProcesoQuery,
  type TiposProcesoPagina,
} from './esquemas/tipo-proceso.js';

// ── Desarrollo, Cotización y Listas de Precios (Módulo 15, F8-E1; D13/R16–R20) ──
export {
  esquemaConceptoCostoCrear,
  esquemaConceptoCostoEditar,
  esquemaConceptoCostoSalida,
  esquemaConceptosCostoQuery,
  esquemaConceptosCostoPagina,
  type DatosConceptoCostoCrear,
  type DatosConceptoCostoEditar,
  type ConceptoCostoSalida,
  type ConceptosCostoQuery,
  type ConceptosCostoPagina,
} from './esquemas/concepto-costo.js';

export {
  esquemaEstadoListaCrear,
  esquemaEstadoListaEditar,
  esquemaEstadoListaSalida,
  esquemaEstadosListaQuery,
  esquemaEstadosListaPagina,
  type DatosEstadoListaCrear,
  type DatosEstadoListaEditar,
  type EstadoListaSalida,
  type EstadosListaQuery,
  type EstadosListaPagina,
} from './esquemas/estado-lista.js';

export {
  esquemaClienteDepartamentoCrear,
  esquemaClienteDepartamentoEditar,
  esquemaClienteDepartamentoSalida,
  esquemaClienteDepartamentosLista,
  type DatosClienteDepartamentoCrear,
  type DatosClienteDepartamentoEditar,
  type ClienteDepartamentoSalida,
  type ClienteDepartamentosLista,
} from './esquemas/cliente-departamento.js';

// ── Factores del cliente para la lista de precios (Módulo 15, F8-E4; D13/R20a) ──
export {
  esquemaClienteFactoresGuardar,
  esquemaClienteFactoresSalida,
  esquemaClienteFactoresLista,
  type DatosClienteFactoresGuardar,
  type ClienteFactoresSalida,
  type ClienteFactoresLista,
} from './esquemas/cliente-factores.js';

export {
  esquemaTelaProveedorColorEntrada,
  esquemaTelaProveedorCrear,
  esquemaTelaProveedorEditar,
  esquemaTelaProveedorPatchCuerpo,
  esquemaTelaProveedorColorSalida,
  esquemaTelaProveedorSalida,
  esquemaTelaProveedoresLista,
  type DatosTelaProveedorColorEntrada,
  type DatosTelaProveedorCrear,
  type DatosTelaProveedorEditar,
  type DatosTelaProveedorPatchCuerpo,
  type TelaProveedorColorSalida,
  type TelaProveedorSalida,
  type TelaProveedoresLista,
} from './esquemas/tela-proveedor.js';

export {
  esquemaModeloAvioTallaEntrada,
  esquemaMedidasAvioGuardar,
  esquemaModeloAvioTallaSalida,
  esquemaModeloAvioMedidasSalida,
  esquemaModoCapturaTalla,
  type ModoCapturaTalla,
  type DatosModeloAvioTallaEntrada,
  type DatosMedidasAvioGuardar,
  type ModeloAvioTallaSalida,
  type ModeloAvioMedidasSalida,
} from './esquemas/modelo-avio-talla.js';

// ── Desarrollo: proyectos + desarrollos (Módulo 15, F8-E2; D13/R16) ──
export {
  ESTADOS_DESARROLLO,
  esquemaEstadoDesarrollo,
  esquemaDesarrolloCrear,
  esquemaDesarrolloModeloNuevoCuerpo,
  esquemaDesarrolloEditar,
  esquemaDesarrolloApagarCuerpo,
  esquemaDesarrolloSalida,
  type EstadoDesarrolloClave,
  type DatosDesarrolloCrear,
  type DatosDesarrolloModeloNuevo,
  type DatosDesarrolloEditar,
  type DatosDesarrolloApagar,
  type DesarrolloSalida,
} from './esquemas/desarrollo.js';

export {
  esquemaProyectoCrear,
  esquemaProyectoEditar,
  esquemaConteosDesarrollo,
  esquemaProyectoSalida,
  esquemaProyectoDetalleSalida,
  esquemaProyectosQuery,
  esquemaProyectosPagina,
  type DatosProyectoCrear,
  type DatosProyectoEditar,
  type ConteosDesarrollo,
  type ProyectoSalida,
  type ProyectoDetalleSalida,
  type ProyectosQuery,
  type ProyectosPagina,
} from './esquemas/proyecto.js';

// ── Precosto persistido por desarrollo (Módulo 15, F8-E3; D13/R17–R19) ──
export {
  esquemaEstadoPrecosto,
  esquemaOrigenPrecostoLinea,
  esquemaPrecostoLineaManualCrear,
  esquemaPrecostoLineaEditar,
  esquemaPrecostoLineaSalida,
  esquemaPrecostoSalida,
  esquemaPrecostoResumen,
  esquemaPrecostosDesarrolloLista,
  type EstadoPrecostoClave,
  type OrigenPrecostoLineaClave,
  type DatosPrecostoLineaManualCrear,
  type DatosPrecostoLineaEditar,
  type PrecostoLineaSalida,
  type PrecostoSalida,
  type PrecostoResumen,
  type PrecostosDesarrolloLista,
} from './esquemas/precosto.js';

// ── Lista de precios por Cliente+Departamento (Módulo 15, F8-E4; D13/R20a) ──
export {
  esquemaListaPreciosCrear,
  esquemaListaFactoresEditar,
  esquemaAjustarPrecioLinea,
  esquemaPrecioTargetLinea,
  esquemaEstadoRenglonLista,
  esquemaCambiarEstadoRenglon,
  ESTADOS_RENGLON_LISTA,
  esquemaListaPreciosLineaSalida,
  esquemaListaPreciosDetalle,
  esquemaListaPreciosResumen,
  esquemaListasPreciosLista,
  esquemaListasPreciosQuery,
  esquemaCandidatoLista,
  esquemaCandidatosLista,
  esquemaCandidatosQuery,
  esquemaLineaDesgloseCosto,
  esquemaGrupoDesgloseCosto,
  esquemaDesgloseCostoLinea,
  type DatosListaPreciosCrear,
  type DatosListaFactoresEditar,
  type DatosAjustarPrecioLinea,
  type DatosPrecioTargetLinea,
  type EstadoRenglonListaSalida,
  type DatosCambiarEstadoRenglon,
  type ListaPreciosLineaSalida,
  type ListaPreciosDetalle,
  type ListaPreciosResumen,
  type ListasPreciosLista,
  type ListasPreciosQuery,
  type CandidatoLista,
  type CandidatosLista,
  type CandidatosQuery,
  type LineaDesgloseCosto,
  type GrupoDesgloseCosto,
  type DesgloseCostoLinea,
} from './esquemas/lista-precios.js';

// ── Negociación por versiones de la lista (Módulo 15, F8-E5; D13/R20b) ──
export {
  esquemaRondaRegistrar,
  esquemaAcuerdoRegistrar,
  esquemaCambiarEstadoLista,
  esquemaSimularNegociacionQuery,
  esquemaNegociacionEventoSalida,
  esquemaNegociacionEventos,
  esquemaSimulacionNegociacion,
  esquemaRenglonMesa,
  esquemaSimularMesaCuerpo,
  esquemaSimulacionMesa,
  esquemaGuardarMesa,
  type DatosRondaRegistrar,
  type DatosAcuerdoRegistrar,
  type DatosCambiarEstadoLista,
  type DatosSimularNegociacion,
  type NegociacionEventoSalida,
  type NegociacionEventos,
  type SimulacionNegociacion,
  type RenglonMesa,
  type DatosSimularMesa,
  type SimulacionMesa,
  type DatosGuardarMesa,
} from './esquemas/negociacion.js';

// ── Cotización: el documento que sale de la mesa (Módulo 15, V1-E7c; §Post-F9.109) ──
export {
  esquemaCotizacionEmitir,
  esquemaCotizacionCancelar,
  esquemaCotizacionLineaSalida,
  esquemaCotizacionDetalle,
  esquemaCotizacionResumen,
  esquemaCotizacionesLista,
  esquemaCotizacionesQuery,
  type DatosCotizacionEmitir,
  type DatosCotizacionCancelar,
  type CotizacionLineaSalida,
  type CotizacionDetalle,
  type CotizacionResumen,
  type CotizacionesLista,
  type CotizacionesQuery,
} from './esquemas/cotizacion.js';

// ── Adjuntos de la orden de producción (R6, F8-E6) ──
export {
  esquemaOrdenAdjuntoCrear,
  esquemaOrdenAdjuntoSubida,
  esquemaOrdenAdjuntoSalida,
  esquemaOrdenAdjuntosLista,
  type DatosOrdenAdjuntoCrear,
  type OrdenAdjuntoSubida,
  type OrdenAdjuntoSalida,
  type OrdenAdjuntosLista,
} from './esquemas/adjunto-orden.js';

// ── Adjuntos / tech pack del desarrollo (rediseño R5, B16) ──
export {
  esquemaDesarrolloAdjuntoCrear,
  esquemaDesarrolloAdjuntoSubida,
  esquemaDesarrolloAdjuntoSalida,
  esquemaDesarrolloAdjuntosLista,
  type DatosDesarrolloAdjuntoCrear,
  type DesarrolloAdjuntoSubida,
  type DesarrolloAdjuntoSalida,
  type DesarrolloAdjuntosLista,
} from './esquemas/adjunto-desarrollo.js';

// ── Medidas de un avío "por medida" (rediseño R5, B11) ──
export {
  esquemaAvioMedidaEntrada,
  esquemaAvioMedidasCuerpo,
  esquemaAvioMedidaSalida,
  esquemaAvioMedidasLista,
  type DatosAvioMedidaEntrada,
  type DatosAvioMedidas,
  type AvioMedidaSalida,
  type AvioMedidasLista,
} from './esquemas/avio-medida.js';

// ── Enganche Desarrollo ↔ Producción (Módulo 15, F8-E6; D13/R16) ──
export {
  esquemaLigarOrdenCuerpo,
  esquemaLigaOrdenSalida,
  esquemaLigaEstadoSalida,
  esquemaCandidatoLigaSalida,
  esquemaSugerenciaLigaSalida,
  esquemaExpedientePrecosto,
  esquemaExpedienteLista,
  esquemaExpedienteOrdenSalida,
  esquemaTableroDesarrollosQuery,
  esquemaTableroDesarrollosSalida,
  type DatosLigarOrden,
  type LigaOrdenSalida,
  type LigaEstadoSalida,
  type CandidatoLigaSalida,
  type SugerenciaLigaSalida,
  type ExpedienteOrdenSalida,
  type TableroDesarrollosQuery,
  type TableroDesarrollosSalida,
} from './esquemas/liga-orden.js';

export {
  DIRECCIONES_MOVIMIENTO,
  ETIQUETAS_DIRECCION_MOVIMIENTO,
  esquemaTipoMovimientoSalida,
  esquemaTiposMovimientoQuery,
  esquemaTiposMovimientoLista,
  type DireccionMovimientoClave,
  type TipoMovimientoSalida,
  type TiposMovimientoQuery,
  type TiposMovimientoLista,
} from './esquemas/tipo-movimiento.js';

// ── Inventario PT operable: movimientos, traspasos, existencias y kardex (F3-E3; doc 04-Inventarios) ──
export {
  esquemaMovimientoPtCrear,
  esquemaTraspasoPtCrear,
  esquemaMovimientoPtCancelarCuerpo,
  esquemaMovimientoPtSalida,
  esquemaTraspasoPtSalida,
  esquemaExistenciasPtQuery,
  esquemaExistenciasPtLista,
  esquemaKardexPtQuery,
  esquemaKardexPtLista,
  esquemaParamFolio,
  type DatosMovPtLineaEntrada,
  type DatosMovimientoPtCrear,
  type DatosTraspasoPtCrear,
  type DatosMovimientoPtCancelar,
  type MovimientoPtSalida,
  type TraspasoPtSalida,
  type ExistenciasPtQuery,
  type ExistenciaPtFila,
  type ExistenciaPtCelda,
  type ExistenciasPtLista,
  type KardexPtQuery,
  type KardexPtRenglon,
  type KardexPtLista,
} from './esquemas/movimiento-pt.js';

// ── Inventario de TELAS y AVÍOS por kardex (Módulo 4, F4-E1; doc 04-Inventarios §B; D5/R4) ──
export {
  esquemaLoteComponenteEntrada,
  esquemaLoteEntrada,
  esquemaAjusteTelaLinea,
  esquemaAjusteTelaCrear,
  esquemaSalidaTelaLinea,
  esquemaSalidaTelaCrear,
  esquemaTraspasoTelaCrear,
  esquemaMovimientoMaterialCancelarCuerpo,
  esquemaMovimientoTelaSalida,
  esquemaTraspasoTelaSalida,
  esquemaExistenciasTelaQuery,
  esquemaExistenciasTelaLista,
  esquemaKardexTelaQuery,
  esquemaKardexTelaLista,
  esquemaTelaColorLinea,
  esquemaTelaColorLineaSalida,
  esquemaAjusteTelaColorCrear,
  esquemaSalidaTelaColorCrear,
  esquemaTraspasoTelaColorCrear,
  esquemaMovimientoTelaColorSalida,
  esquemaTraspasoTelaColorSalida,
  esquemaExistenciasTelaColorQuery,
  esquemaExistenciasTelaColorLista,
  esquemaKardexTelaColorQuery,
  esquemaKardexTelaColorLista,
  esquemaPartidasTelaQuery,
  esquemaPartidasTelaLista,
  esquemaAjusteAvioLinea,
  esquemaAjusteAvioCrear,
  esquemaTraspasoAvioCrear,
  esquemaMovimientoAvioSalida,
  esquemaTraspasoAvioSalida,
  esquemaExistenciasAvioQuery,
  esquemaExistenciasAvioLista,
  esquemaKardexAvioQuery,
  esquemaKardexAvioLista,
  esquemaParamIdMaterial,
  type DatosLoteComponenteEntrada,
  type DatosLoteEntrada,
  type DatosAjusteTelaLinea,
  type DatosAjusteTelaCrear,
  type DatosSalidaTelaCrear,
  type DatosTraspasoTelaCrear,
  type DatosMovimientoMaterialCancelar,
  type MovimientoTelaSalida,
  type TraspasoTelaSalida,
  type ExistenciasTelaQuery,
  type ExistenciaTelaFila,
  type ExistenciasTelaLista,
  type KardexTelaQuery,
  type KardexTelaRenglon,
  type KardexTelaLista,
  type DatosTelaColorLinea,
  type DatosTelaColorLineaSalida,
  type DatosAjusteTelaColorCrear,
  type DatosSalidaTelaColorCrear,
  type DatosTraspasoTelaColorCrear,
  type MovimientoTelaColorSalida,
  type TraspasoTelaColorSalida,
  type ExistenciasTelaColorQuery,
  type ExistenciaTelaColorHijo,
  type ExistenciaTelaAgrupada,
  type ExistenciasTelaColorLista,
  type KardexTelaColorQuery,
  type KardexTelaColorRenglon,
  type KardexTelaColorLista,
  type PartidasTelaQuery,
  type PartidaTelaSalida,
  type PartidasTelaLista,
  type DatosAjusteAvioLinea,
  type DatosAjusteAvioCrear,
  type DatosTraspasoAvioCrear,
  type MovimientoAvioSalida,
  type TraspasoAvioSalida,
  type ExistenciasAvioQuery,
  type ExistenciaAvioFila,
  type ExistenciasAvioLista,
  type KardexAvioQuery,
  type KardexAvioRenglon,
  type KardexAvioLista,
} from './esquemas/inventario-material.js';

// ── Entrada de tela por FACTURA/REMISIÓN sin OC (B1; DECISIONES §Post-F9.9 p.7) ──
export {
  esquemaTipoDocumentoEntradaTela,
  esquemaEstatusEntradaTela,
  esquemaEntradaTelaLineaEntrada,
  esquemaEntradaTelaCrear,
  esquemaEntradaTelaActualizar,
  esquemaEntradaTelaCancelarCuerpo,
  esquemaEntradaTelaLineaSalida,
  esquemaEntradaTelaSalida,
  esquemaEntradasTelaQuery,
  esquemaEntradasTelaPagina,
  esquemaParamIdEntradaTela,
  esquemaEntradaTelaAdjuntoCrear,
  esquemaEntradaTelaAdjuntoSubida,
  esquemaEntradaTelaAdjuntoSalida,
  esquemaEntradaTelaAdjuntosLista,
  esquemaConceptoCfdiEntradaTela,
  esquemaPropuestaCfdiEntradaTela,
  esquemaLeerCfdiEntradaTela,
  type PropuestaCfdiEntradaTelaSalida,
  type DatosLeerCfdiEntradaTela,
  type TipoDocumentoEntradaTela,
  type EstatusEntradaTela,
  type DatosEntradaTelaLineaEntrada,
  type DatosEntradaTelaCrear,
  type DatosEntradaTelaActualizar,
  type DatosEntradaTelaCancelar,
  type EntradaTelaLineaSalida,
  type EntradaTelaSalida,
  type EntradasTelaQuery,
  type EntradasTelaPagina,
  type DatosEntradaTelaAdjuntoCrear,
  type EntradaTelaAdjuntoSubida,
  type EntradaTelaAdjuntoSalida,
  type EntradaTelaAdjuntosLista,
} from './esquemas/entrada-tela.js';

// ── Etapas de producción: corte + envío a maquila (F3-E2; doc 03-Produccion) ──
export {
  esquemaCorteCrear,
  esquemaEnvioCrear,
  esquemaEtapaCancelarCuerpo,
  esquemaEtapaSalida,
  esquemaEtapasOrdenLista,
  esquemaEtapasOrdenQuery,
  esquemaPendientesOrden,
  esquemaSugerenciaCaptura,
  esquemaSugerenciaCapturaQuery,
  esquemaCorteSemanalQuery,
  esquemaCorteSemanalLista,
  type DatosCorteCrear,
  type DatosEnvioCrear,
  type DatosEtapaCancelar,
  type DatosEtapaLineaEntrada,
  type EtapaSalida,
  type EtapasOrdenLista,
  type EtapasOrdenQuery,
  type PendientesOrden,
  type SugerenciaCaptura,
  type SugerenciaCapturaQuery,
  type CorteSemanalQuery,
  type CorteSemanalLista,
} from './esquemas/etapa.js';

// ── Recibo de maquila (F3-E4; doc 03-Produccion Paso 5) ──────────────────────
export {
  esquemaReciboCrear,
  esquemaReciboCancelarCuerpo,
  esquemaReciboSalida,
  esquemaPendientesRecibir,
  esquemaRecibosSemanalesQuery,
  esquemaRecibosSemanalesLista,
  type DatosReciboLineaEntrada,
  type DatosReciboCrear,
  type DatosReciboCancelar,
  type ReciboSalida,
  type PendientesRecibir,
  type RecibosSemanalesQuery,
  type RecibosSemanalesLista,
} from './esquemas/recibo.js';

// ── Cargos EsMa: cola de validación derivada de los recibos (F3-E4; doc 07-EsMa) ──
// ── + Movimientos (abonos/descuentos/pagos), saldos, conciliación y orden pagada (F6-E4) ──
export {
  esquemaCargoEsMaValidarCuerpo,
  esquemaCargosEsMaQuery,
  esquemaCargoEsMaSalida,
  esquemaCargosEsMaLista,
  MODALIDADES_FACTURACION,
  ETIQUETAS_MODALIDAD_FACTURACION,
  ESTADOS_REVISION_ESMA,
  CONCEPTOS_MOVIMIENTO_ESMA,
  esquemaMovimientoEsMaCrear,
  esquemaAbonoCrear,
  esquemaDescuentoCrear,
  esquemaPagoAplicacionEntrada,
  esquemaPagoCrear,
  esquemaMovimientoEsMaSalida,
  esquemaMovimientosEsMaLista,
  esquemaPagoAplicacionSalida,
  esquemaPagoSalida,
  esquemaPagosLista,
  esquemaSaldoQuery,
  esquemaSaldoSalida,
  esquemaConciliacionQuery,
  esquemaConciliacionFila,
  esquemaCargoSinReciboFila,
  esquemaConciliacionSalida,
  esquemaOrdenPagadaForzarCuerpo,
  esquemaOrdenPagadaSalida,
  // F6-E5: estado de cuenta, desglosado, saldos de todos, semanales, selector y revisión.
  CONCEPTOS_ESTADO_CUENTA,
  TIPOS_MAQUILERO_ESMA,
  esquemaEstadoCuentaQuery,
  esquemaEstadoCuentaMovimiento,
  esquemaEstadoCuentaSalida,
  // V1-E8k: prendas incompletas entregadas (informativo, fuera del saldo — §Post-F9.136).
  esquemaIncompletaEntregada,
  esquemaIncompletasBloque,
  esquemaDesglosadoCargo,
  esquemaDesglosadoSalida,
  esquemaSaldosTodosQuery,
  esquemaSaldoTodosFila,
  esquemaSaldosTodosSalida,
  esquemaPagosSemanalesQuery,
  esquemaPagoSemanalFila,
  esquemaPagosSemanalesSalida,
  esquemaRecibosSemanalesEsMaQuery,
  esquemaReciboSemanalEsMaFila,
  esquemaRecibosSemanalesEsMaSalida,
  esquemaMaquilerosEsMaQuery,
  esquemaMaquileroEsMaFila,
  esquemaMaquilerosEsMaLista,
  esquemaRevisionSalida,
  type DatosCargoEsMaValidar,
  type CargosEsMaQuery,
  type CargoEsMaSalida,
  type CargosEsMaLista,
  type ModalidadFacturacionClave,
  type EstadoRevisionEsMaClave,
  type ConceptoMovimientoEsMaClave,
  type DatosMovimientoEsMaCrear,
  type DatosPagoCrear,
  type IncompletaEntregadaSalida,
  type IncompletasBloqueSalida,
  type MovimientoEsMaSalida,
  type MovimientosEsMaLista,
  type PagoSalida,
  type PagosLista,
  type SaldoQuery,
  type SaldoSalida,
  type ConciliacionQuery,
  type ConciliacionSalida,
  type DatosOrdenPagadaForzar,
  type OrdenPagadaSalida,
  type ConceptoEstadoCuentaClave,
  type EstadoCuentaQuery,
  type EstadoCuentaMovimiento,
  type EstadoCuentaSalida,
  type DesglosadoCargo,
  type DesglosadoSalida,
  type SaldosTodosQuery,
  type SaldoTodosFila,
  type SaldosTodosSalida,
  type PagosSemanalesQuery,
  type PagoSemanalFila,
  type PagosSemanalesSalida,
  type RecibosSemanalesEsMaQuery,
  type ReciboSemanalEsMaFila,
  type RecibosSemanalesEsMaSalida,
  type TipoMaquileroEsMaClave,
  type MaquilerosEsMaQuery,
  type MaquileroEsMaFila,
  type MaquilerosEsMaLista,
  type RevisionSalida,
} from './esquemas/esma.js';

// ── Motor de cuenta corriente de terceros (Módulo 14, F9-E1; D12/D15/R10) ──
export {
  TIPOS_TERCERO,
  ORIGENES_MOVIMIENTO_TERCERO,
  ETIQUETAS_ORIGEN_MOVIMIENTO_TERCERO,
  VISTAS_TERCERO,
  SEGMENTOS_FACTURACION,
  FUENTES_MOVIMIENTO_TERCERO,
  esquemaLimitesAging,
  esquemaMovimientoTerceroCrear,
  esquemaMovimientoTerceroCancelar,
  esquemaMovimientoTerceroSalida,
  esquemaSaldoTerceroSalida,
  esquemaEstadoCuentaTerceroQuery,
  esquemaEstadoCuentaTerceroSalida,
  type TipoTerceroClave,
  type OrigenMovimientoTerceroClave,
  type VistaTerceroClave,
  type SegmentoFacturacionClave,
  type FuenteMovimientoTerceroClave,
  type LimitesAgingSalida,
  type DatosMovimientoTerceroCrear,
  type DatosMovimientoTerceroCancelar,
  type MovimientoTerceroSalida,
  type SaldoTerceroSalida,
  type EstadoCuentaTerceroQuery,
  type EstadoCuentaTerceroSalida,
} from './esquemas/terceros.js';

// ── CxP: cuentas por pagar de proveedores (Módulo 14, F9-E2; D12/D15/R10) ──
export {
  ORIGENES_MOVIMIENTO_CXP,
  ETIQUETAS_ORIGEN_CXP,
  FILTROS_BANDEJA_CXP,
  esquemaMovimientoCxpCrear,
  esquemaBandejaCxpQuery,
  esquemaBandejaCxpFila,
  esquemaResumenCxpSalida,
  esquemaBandejaCxpSalida,
  type OrigenMovimientoCxpClave,
  type FiltroBandejaCxpClave,
  type DatosMovimientoCxpCrear,
  type BandejaCxpQuery,
  type BandejaCxpFila,
  type ResumenCxpSalida,
  type BandejaCxpSalida,
} from './esquemas/cxp.js';

// ── Importación de CFDI de proveedores (Módulo 14, F9-E3; D12/R11) ──
export {
  TIPOS_COMPROBANTE_CFDI,
  ETIQUETAS_TIPO_COMPROBANTE_CFDI,
  REF_TIPOS_CFDI,
  esquemaCfdiConcepto,
  esquemaCfdiDatos,
  esquemaCfdiCandidatoProveedor,
  esquemaCfdiCandidatoOc,
  esquemaCfdiXml,
  esquemaCfdiPrevisualizacion,
  esquemaCfdiImportarEntrada,
  esquemaCfdiImportarSalida,
  type TipoComprobanteCfdiClave,
  type RefTipoCfdiClave,
  type CfdiDatos,
  type CfdiCandidatoProveedor,
  type CfdiCandidatoOc,
  type DatosCfdiXml,
  type CfdiPrevisualizacion,
  type DatosCfdiImportar,
  type CfdiImportarSalida,
} from './esquemas/cfdi.js';

// ── CxC: cuentas por cobrar de clientes (Módulo 14, F9-E4; D12/D15/R10/R12) ──
export {
  ORIGENES_MOVIMIENTO_CXC,
  ETIQUETAS_ORIGEN_CXC,
  FILTROS_BANDEJA_CXC,
  esquemaMovimientoCxcCrear,
  esquemaBandejaCxcQuery,
  esquemaBandejaCxcFila,
  esquemaResumenCxcSalida,
  esquemaBandejaCxcSalida,
  type OrigenMovimientoCxcClave,
  type FiltroBandejaCxcClave,
  type DatosMovimientoCxcCrear,
  type BandejaCxcQuery,
  type BandejaCxcFila,
  type ResumenCxcSalida,
  type BandejaCxcSalida,
} from './esquemas/cxc.js';

// ── Importación de CFDI de ventas (Módulo 14, F9-E4; D12/R12) ──
export {
  REF_TIPOS_CFDI_VENTA,
  esquemaCfdiVentaDatos,
  esquemaCfdiCandidatoCliente,
  esquemaCfdiCandidatoPedido,
  esquemaCfdiVentaPrevisualizacion,
  esquemaCfdiVentaImportarEntrada,
  esquemaCfdiVentaImportarSalida,
  type RefTipoCfdiVentaClave,
  type CfdiVentaDatos,
  type CfdiCandidatoCliente,
  type CfdiCandidatoPedido,
  type CfdiVentaPrevisualizacion,
  type DatosCfdiVentaImportar,
  type CfdiVentaImportarSalida,
} from './esquemas/cfdi-ventas.js';

// ── Reportes fiscales para el contador (Módulo 14, F9-E5; D12/R13) ──
export {
  TIPOS_MOVIMIENTO_FISCAL,
  FILTROS_CFDI,
  esquemaReporteFiscalQuery,
  esquemaReporteFiscalFila,
  esquemaTotalesFiscales,
  esquemaReporteFiscalSalida,
  esquemaSaludFiscalQuery,
  esquemaSaldoFiscalTercero,
  esquemaSaludFiscalSalida,
  type TipoMovimientoFiscalClave,
  type FiltroCfdiClave,
  type ReporteFiscalQuery,
  type ReporteFiscalFila,
  type TotalesFiscales,
  type ReporteFiscalSalida,
  type SaludFiscalQuery,
  type SaldoFiscalTercero,
  type SaludFiscalSalida,
} from './esquemas/reportes-fiscales.js';

// ── Entrega a cliente: cierre del ciclo de la orden (F3-E5; doc 03-Produccion) ──
export {
  esquemaEntregaClienteCrear,
  esquemaEntregaClienteCancelarCuerpo,
  esquemaEntregaClienteSalida,
  esquemaEntregasOrdenLista,
  esquemaSeguimientoEntregaOrden,
  esquemaSeguimientoEntregaQuery,
  type DatosEntregaLineaEntrada,
  type DatosEntregaClienteCrear,
  type DatosEntregaClienteCancelar,
  type EntregaClienteSalida,
  type EntregasOrdenLista,
  type SeguimientoEntregaOrden,
  type SeguimientoEntregaQuery,
} from './esquemas/entrega-cliente.js';

// ── Costos: motor de costeo (Módulo 6, F7-E1; doc 06-Costos-y-EDR; D1/D2) ──
export {
  esquemaBaseProrrateo,
  esquemaPreCostoModelo,
  esquemaListaPreciosQuery,
  esquemaListaPreciosFila,
  esquemaListaPreciosSalida,
  esquemaCostoOrdenSalida,
  esquemaCostoOrdenGuardarCuerpo,
  esquemaOrigenPrecioReal,
  esquemaOrigenRequerido,
  esquemaCostoRealResumen,
  esquemaCostoRealOrdenSalida,
  esquemaListaCostosQuery,
  esquemaListaCostosFila,
  esquemaListaCostosPagina,
  esquemaMargenesQuery,
  esquemaMargenPedidoFila,
  esquemaMargenesSalida,
  type BaseProrrateo,
  type PreCostoModelo,
  type ListaPreciosQuery,
  type ListaPreciosSalida,
  type CostoOrdenSalida,
  type CostoOrdenGuardarCuerpo,
  type OrigenPrecioReal,
  type OrigenRequerido,
  type CostoRealResumen,
  type CostoRealOrdenSalida,
  type ListaCostosQuery,
  type ListaCostosPagina,
  type MargenesQuery,
  type MargenesSalida,
} from './esquemas/costos.js';

// ── EDR: Estado de Resultados mensual (Módulo 6, F7-E2; doc 06-Costos-y-EDR §4; D1/D2) ──
export {
  esquemaEdrOrigenLinea,
  esquemaEdrGenerarCuerpo,
  esquemaEdrEncabezadoCuerpo,
  esquemaEdrLineaAjustarCuerpo,
  esquemaEdrLineaManualCuerpo,
  esquemaEdrLineasQuery,
  esquemaEdrPorMesQuery,
  esquemaEdrPorAnioQuery,
  esquemaEdrEncabezadoSalida,
  esquemaEdrLineaSalida,
  esquemaEdrCorteSalida,
  esquemaEdrCalculado,
  esquemaEdrPorMesSalida,
  esquemaEdrLineasSalida,
  esquemaEdrPorAnioMes,
  esquemaEdrPorAnioEmpresa,
  esquemaEdrPorAnioSalida,
  type EdrOrigenLineaClave,
  type DatosEdrGenerar,
  type DatosEdrEncabezado,
  type DatosEdrLineaAjustar,
  type DatosEdrLineaManual,
  type EdrLineasQuery,
  type EdrPorMesQuery,
  type EdrPorAnioQuery,
  type EdrEncabezadoSalida,
  type EdrLineaSalida,
  type EdrCorteSalida,
  type EdrCalculado,
  type EdrPorMesSalida,
  type EdrLineasSalida,
  type EdrPorAnioMes,
  type EdrPorAnioEmpresa,
  type EdrPorAnioSalida,
} from './esquemas/edr.js';

// ── Ventas: vista comercial de la facturación por modelo sobre el EDR (proto vVentas; F7-E2) ──
export {
  esquemaVentasQuery,
  esquemaVentaLinea,
  esquemaVentasResumen,
  esquemaVentasSalida,
  type VentasQuery,
  type VentaLinea,
  type VentasResumen,
  type VentasSalida,
} from './esquemas/ventas.js';

// ── Indicadores: tableros directivos calculados en segundo plano (Módulo Indicadores, F7-E3; plan §11) ──
export {
  esquemaKpisRcQuery,
  esquemaKpisRc,
  esquemaKpisCalidadQuery,
  esquemaKpisCalidad,
  esquemaKpisWipQuery,
  esquemaKpisWip,
  esquemaRefrescoEncolado,
  type KpisRcQuery,
  type KpisRc,
  type KpisCalidadQuery,
  type KpisCalidad,
  type KpisWipQuery,
  type KpisWip,
  type RefrescoEncolado,
} from './esquemas/indicadores.js';

// ── Productividad unificada IP/Almacén (Módulo Indicadores, F7-E4; doc 05 §A.1/§B.1; MEJORAS 05 §1) ──
export {
  esquemaAreaProductividad,
  esquemaPersonalCrear,
  esquemaPersonalEditar,
  esquemaPersonalSalida,
  esquemaPersonalQuery,
  esquemaPersonalPagina,
  esquemaActividadCrear,
  esquemaActividadEditar,
  esquemaActividadSalida,
  esquemaActividadQuery,
  esquemaActividadPagina,
  esquemaRegistroProductividadCrear,
  esquemaRegistroProductividadCancelar,
  esquemaRegistroProductividadSalida,
  esquemaRegistroProductividadQuery,
  esquemaRegistroProductividadPagina,
  esquemaAgrupacionTablero,
  esquemaTableroProductividadQuery,
  esquemaTableroProductividad,
  type DatosPersonalCrear,
  type DatosPersonalEditar,
  type PersonalSalida,
  type PersonalQuery,
  type PersonalPagina,
  type DatosActividadCrear,
  type DatosActividadEditar,
  type ActividadSalida,
  type ActividadQuery,
  type ActividadPagina,
  type DatosRegistroProductividadCrear,
  type DatosRegistroProductividadCancelar,
  type RegistroProductividadSalida,
  type RegistroProductividadQuery,
  type RegistroProductividadPagina,
  type TableroProductividadQuery,
  type TableroProductividad,
} from './esquemas/productividad.js';

// ── Fichas confiables (Módulo Indicadores, F7-E4; doc 05 §A.2; ex IP_InfConf) ──
export {
  esquemaReactivoFichaCrear,
  esquemaReactivoFichaEditar,
  esquemaReactivoFichaSalida,
  esquemaReactivosFichaQuery,
  esquemaReactivosFichaLista,
  esquemaVerificarFichaOrden,
  esquemaFichaOrdenSalida,
  esquemaFichasConfiablesQuery,
  esquemaFichasConfiables,
  type DatosReactivoFichaCrear,
  type DatosReactivoFichaEditar,
  type ReactivoFichaSalida,
  type ReactivosFichaQuery,
  type ReactivosFichaLista,
  type DatosVerificarFichaOrden,
  type FichaOrdenSalida,
  type FichasConfiablesQuery,
  type FichasConfiables,
} from './esquemas/fichas-confiables.js';

// ── Muestrarios pendientes (Módulo Indicadores, F7-E4; doc 05 §A.3; ex IP_MuesPend) ──
export {
  esquemaMuestrarioCrear,
  esquemaMuestrarioEditar,
  esquemaMuestrarioEntregar,
  esquemaMuestrarioCancelar,
  esquemaEstadoMuestrario,
  esquemaMuestrarioSalida,
  esquemaMuestrariosQuery,
  esquemaMuestrariosPagina,
  esquemaMuestrariosCumplimientoQuery,
  esquemaMuestrariosCumplimiento,
  type EstadoMuestrarioValor,
  type DatosMuestrarioCrear,
  type DatosMuestrarioEditar,
  type DatosMuestrarioEntregar,
  type DatosMuestrarioCancelar,
  type MuestrarioSalida,
  type MuestrariosQuery,
  type MuestrariosPagina,
  type MuestrariosCumplimientoQuery,
  type MuestrariosCumplimiento,
} from './esquemas/muestrarios.js';

// ── Inventario cíclico (Módulo Indicadores / Almacén, F7-E5; doc 05; ex Alm_IC_*) ──
export {
  esquemaEstadoInventarioCiclico,
  esquemaInventarioCiclicoCrear,
  esquemaConteoRenglonEntrada,
  esquemaInventarioCiclicoConteo,
  esquemaInventarioCiclicoCancelar,
  esquemaInventarioCiclicoResumen,
  esquemaInventariosCiclicosQuery,
  esquemaInventariosCiclicosPagina,
  esquemaConteoRenglon,
  esquemaConteoSalida,
  esquemaExactitudRenglon,
  esquemaExactitudTotales,
  esquemaExactitudSalida,
  type EstadoInventarioCiclicoValor,
  type DatosInventarioCiclicoCrear,
  type DatosInventarioCiclicoConteo,
  type DatosInventarioCiclicoCancelar,
  type InventarioCiclicoResumen,
  type InventariosCiclicosQuery,
  type InventariosCiclicosPagina,
  type ConteoSalida,
  type ExactitudSalida,
} from './esquemas/inventario-ciclico.js';

// ── Tablero WIP + existencias en poder del maquilero (F3-E5; doc 03-Produccion form Proceso/MaqExis) ──
export {
  esquemaTableroWipQuery,
  esquemaWipOrdenFila,
  esquemaWipTotales,
  esquemaTableroWipPagina,
  esquemaWipOrden,
  esquemaExistenciaMaquileroQuery,
  esquemaExistenciaMaquileroFila,
  esquemaExistenciaMaquileroLista,
  type TableroWipQuery,
  type WipOrdenFila,
  type WipTotales,
  type TableroWipPagina,
  type WipOrden,
  type WipMaquileroPendiente,
  type ExistenciaMaquileroQuery,
  type ExistenciaMaquileroFila,
  type ExistenciaMaquileroLista,
} from './esquemas/wip.js';

// ── Ruta Crítica: catálogo configurable de procesos (Módulo 8, F5-E1; doc 08-Ruta-Critica) ──
export {
  CONDICIONES_APLICABILIDAD,
  ETIQUETAS_CONDICION_APLICABILIDAD,
  TIPOS_EVENTO_PROCESO,
  ETIQUETAS_TIPO_EVENTO_PROCESO,
  TIPOS_DURACION_PROCESO,
  ETIQUETAS_TIPO_DURACION_PROCESO,
  esquemaProcesoCrear,
  esquemaProcesoEditar,
  esquemaProcesoPatchCuerpo,
  esquemaProcesoRolesCuerpo,
  esquemaProcesoDependenciasCuerpo,
  esquemaChecklistItemEntrada,
  esquemaProcesoChecklistCuerpo,
  esquemaProcesoRolSalida,
  esquemaProcesoAntecesorSalida,
  esquemaChecklistItemSalida,
  esquemaProcesoSalida,
  esquemaProcesosQuery,
  esquemaProcesosPagina,
  type CondicionAplicabilidadClave,
  type TipoEventoProcesoClave,
  type TipoDuracionProcesoClave,
  type DatosProcesoCrear,
  type DatosProcesoEditar,
  type DatosProcesoPatchCuerpo,
  type DatosProcesoRoles,
  type DatosProcesoDependencias,
  type DatosChecklistItemEntrada,
  type DatosProcesoChecklist,
  type ProcesoRolSalida,
  type ProcesoAntecesorSalida,
  type ChecklistItemSalida,
  type ProcesoSalida,
  type ProcesosQuery,
  type ProcesosPagina,
} from './esquemas/ruta-critica.js';

// ── Ruta Crítica: plantillas, reglas de duración y calendario (Módulo 8, F5-E2) ──
export {
  esquemaParamIdRc,
  esquemaListarRcQuery,
  esquemaFamiliaCrear,
  esquemaFamiliaPatchCuerpo,
  esquemaFamiliaSalida,
  esquemaArticuloCrear,
  esquemaArticuloPatchCuerpo,
  esquemaArticuloSalida,
  esquemaPlantillaProcesoEntrada,
  esquemaPlantillaCrear,
  esquemaPlantillaPatchCuerpo,
  esquemaPlantillaProcesoSalida,
  esquemaPlantillaSalida,
  esquemaFactorCantidadCrear,
  esquemaFactorCantidadPatchCuerpo,
  esquemaFactorCantidadSalida,
  esquemaDuracionTelaCrear,
  esquemaDuracionTelaPatchCuerpo,
  esquemaDuracionTelaSalida,
  esquemaDuracionAplicacionCrear,
  esquemaDuracionAplicacionPatchCuerpo,
  esquemaDuracionAplicacionSalida,
  esquemaRangoDificultadCrear,
  esquemaRangoDificultadPatchCuerpo,
  esquemaRangoDificultadSalida,
  esquemaCalendarioActualizar,
  esquemaCalendarioSalida,
  esquemaFestivosQuery,
  esquemaFestivoCrear,
  esquemaFestivoPatchCuerpo,
  esquemaFestivoSalida,
  type ListarRcQuery,
  type DatosFamiliaCrear,
  type DatosFamiliaPatchCuerpo,
  type FamiliaSalida,
  type DatosArticuloCrear,
  type DatosArticuloPatchCuerpo,
  type ArticuloSalida,
  type DatosPlantillaProcesoEntrada,
  type DatosPlantillaCrear,
  type DatosPlantillaPatchCuerpo,
  type PlantillaProcesoSalida,
  type PlantillaSalida,
  type DatosFactorCantidadCrear,
  type DatosFactorCantidadPatchCuerpo,
  type FactorCantidadSalida,
  type DatosDuracionTelaCrear,
  type DatosDuracionTelaPatchCuerpo,
  type DuracionTelaSalida,
  type DatosDuracionAplicacionCrear,
  type DatosDuracionAplicacionPatchCuerpo,
  type DuracionAplicacionSalida,
  type DatosRangoDificultadCrear,
  type DatosRangoDificultadPatchCuerpo,
  type RangoDificultadSalida,
  type DatosCalendarioActualizar,
  type CalendarioSalida,
  type FestivosQuery,
  type DatosFestivoCrear,
  type DatosFestivoPatchCuerpo,
  type FestivoSalida,
} from './esquemas/ruta-critica-plantillas.js';

// ── Ruta Crítica: motor de la ruta viva por orden (Módulo 8, F5-E3) ──
export {
  esquemaParamOrdenRc,
  esquemaParamRutaProceso,
  esquemaParamChecklistItem,
  esquemaProgramarRc,
  esquemaAjusteAgregar,
  esquemaAjusteDependencia,
  esquemaAjustarRuta,
  esquemaCapturarProceso,
  esquemaMarcarChecklist,
  esquemaEstadoSemaforo,
  esquemaSecuenciaEstampadoCuerpo,
  esquemaRutaChecklistSalida,
  esquemaRutaProcesoSalida,
  esquemaRutaOrdenSalida,
  type DatosProgramarRc,
  type DatosAjustarRuta as DatosAjustarRutaContrato,
  type DatosCapturarProceso,
  type DatosMarcarChecklist,
  type DatosSecuenciaEstampado,
  type RutaOrdenSalida,
} from './esquemas/ruta-critica-programacion.js';

// ── Ruta Crítica: hitos de la orden (cierre del hueco de emisores, post-F9) ──
export {
  TIPOS_HITO_ORDEN,
  esquemaParamOrdenHito,
  esquemaRegistrarHitoCuerpo,
  esquemaCancelarHitoCuerpo,
  esquemaHitoOrdenSalida,
  esquemaHitosOrdenSalida,
  type TipoHitoOrdenClave,
  type DatosRegistrarHito,
  type DatosCancelarHito,
  type HitoOrdenSalida,
  type HitosOrdenSalida,
} from './esquemas/ruta-critica-hitos.js';

// ── Ruta Crítica: bandeja "mis tareas" + conteo de alertas (Módulo 8, F5-E5; R4) ──
export {
  esquemaBandejaRcQuery,
  esquemaBandejaChecklistSalida,
  esquemaBandejaTareaSalida,
  esquemaBandejaRcPagina,
  esquemaAlertasRcConteo,
  esquemaUrgenciaPendiente,
  esquemaTipoEventoRc,
  esquemaResumenPendientesQuery,
  esquemaResumenProcesoPendiente,
  esquemaResumenPendientes,
  esquemaResponsableRc,
  esquemaResponsablesRc,
  type BandejaRcQuery,
  type BandejaTareaSalida,
  type BandejaRcPagina,
  type AlertasRcConteo,
  type UrgenciaPendiente,
  type TipoEventoRcContrato,
  type ResumenPendientesQuery,
  type ResumenPendientes,
  type ResponsableRc,
} from './esquemas/ruta-critica-bandeja.js';

// ── Ruta Crítica: concentrado "planeado vs real" (Módulo 8, F5-E7) ──
export {
  ORDENES_CONCENTRADO,
  esquemaConcentradoQuery,
  esquemaConcentradoProceso,
  esquemaConcentradoFila,
  esquemaConcentradoPagina,
  type OrdenConcentradoClave,
  type ConcentradoQuery,
  type ConcentradoProceso,
  type ConcentradoFila,
  type ConcentradoPagina,
} from './esquemas/ruta-critica-concentrado.js';

// ── Ruta Crítica: tablero de gestión "Análisis RC" (Módulo 8, rediseño R7, B14) ──
export {
  esquemaOrdenAtencion,
  esquemaAnalisisSalud,
  esquemaEntregaCiclo,
  esquemaOrdenAlerta,
  esquemaRiesgoCliente,
  esquemaCuelloProceso,
  esquemaAnalisisRc,
  esquemaBadgeDesempeno,
  esquemaPersonaDesempeno,
  esquemaParametrosDesempeno,
  esquemaDesempenoRc,
  type OrdenAtencion,
  type OrdenAlerta,
  type RiesgoCliente,
  type CuelloProceso,
  type AnalisisRc,
  type BadgeDesempeno,
  type PersonaDesempeno,
  type DesempenoRc,
} from './esquemas/ruta-critica-analisis.js';

// ── Calidad: base configurable — defectos, tipos de producto y planes AQL (Módulo 8, F6-E1) ──
export {
  SEVERIDADES_DEFECTO,
  ETIQUETAS_SEVERIDAD_DEFECTO,
  NIVELES_AQL,
  esquemaDigitoConcepto,
  esquemaTipoProductoCrear,
  esquemaTipoProductoEditar,
  esquemaTipoProductoSalida,
  esquemaTiposProductoQuery,
  esquemaTiposProductoPagina,
  esquemaDefectoCrear,
  esquemaDefectoEditar,
  esquemaDefectoTipoSalida,
  esquemaDefectoSalida,
  esquemaDefectosQuery,
  esquemaDefectosPagina,
  esquemaPlanLimiteEntrada,
  esquemaPlanRenglonEntrada,
  esquemaPlanAqlCrear,
  esquemaPlanAqlEditar,
  esquemaPlanLimiteSalida,
  esquemaPlanRenglonSalida,
  esquemaPlanAqlSalida,
  esquemaPlanesAqlQuery,
  esquemaPlanesAqlPagina,
  esquemaResolverPlanQuery,
  esquemaResolverPlanSalida,
  type SeveridadDefectoClave,
  type NivelAqlClave,
  type DatosTipoProductoCrear,
  type DatosTipoProductoEditar,
  type TipoProductoSalida,
  type TiposProductoQuery,
  type TiposProductoPagina,
  type DatosDefectoCrear,
  type DatosDefectoEditar,
  type DefectoSalida,
  type DefectosQuery,
  type DefectosPagina,
  type DatosPlanAqlCrear,
  type DatosPlanAqlEditar,
  type PlanAqlSalida,
  type PlanesAqlQuery,
  type PlanesAqlPagina,
  type ResolverPlanQuery,
  type ResolverPlanSalida,
} from './esquemas/calidad.js';

// ── Calidad: catálogo de auditores (Módulo 8, rediseño R9 — proto `CAT_AUDITORES`) ──
export {
  ROLES_AUDITOR,
  NIVELES_AQL_AUDITOR,
  esquemaAuditorCrear,
  esquemaAuditorEditar,
  esquemaAuditorSalida,
  esquemaAuditoresQuery,
  esquemaAuditoresPagina,
  type RolAuditorClave,
  type NivelAqlAuditorClave,
  type DatosAuditorCrear,
  type DatosAuditorEditar,
  type AuditorSalida,
  type AuditoresQuery,
  type AuditoresPagina,
} from './esquemas/auditor.js';

// ── Calidad — núcleo de auditorías (F6-E2) ──
export {
  RESULTADOS_AUDITORIA,
  ETIQUETAS_RESULTADO_AUDITORIA,
  TIPOS_AUDITORIA,
  ETIQUETAS_TIPO_AUDITORIA,
  SUGERENCIAS_AQL,
  esquemaAuditoriaCrear,
  esquemaAuditoriaDefectoEntrada,
  esquemaAuditoriaResultadoCuerpo,
  esquemaReclasificacionCuerpo,
  esquemaSugerenciaNivel,
  esquemaSugerenciaAql,
  esquemaAuditoriaDefectoSalida,
  esquemaAuditoriaSalida,
  esquemaMaquileroPropuesto,
  esquemaMuestraNivel,
  esquemaMuestraPropuesta,
  esquemaAuditoriaContexto,
  esquemaAuditoriaResumen,
  esquemaAuditoriasQuery,
  esquemaAuditoriasPagina,
  esquemaAuditoriaModificarCuerpo,
  esquemaAuditoriaCancelarCuerpo,
  esquemaHistorialMaquileroQuery,
  esquemaHistorialMaquileroSalida,
  esquemaResumenAuditoriasQuery,
  esquemaDefectoPrincipal,
  esquemaResumenAuditorias,
  type ResultadoAuditoriaClave,
  type TipoAuditoriaClave,
  type SugerenciaAqlClave,
  type DatosAuditoriaCrear,
  type DatosAuditoriaResultado,
  type DatosReclasificacion,
  type SugerenciaAqlSalida,
  type AuditoriaSalida,
  type AuditoriaContextoSalida,
  type AuditoriaResumenSalida,
  type AuditoriasQuery,
  type AuditoriasPagina,
  type DatosAuditoriaModificar,
  type DatosAuditoriaCancelar,
  type HistorialMaquileroQuery,
  type HistorialMaquileroSalida,
  type ResumenAuditoriasQuery,
  type DefectoPrincipal,
  type ResumenAuditorias,
} from './esquemas/auditorias.js';

// ── Bitácora: consulta del log de auditoría A7 (transversal, F6-E1) ──
export {
  ACCIONES_BITACORA,
  ETIQUETAS_ACCION_BITACORA,
  esquemaBitacoraSalida,
  esquemaBitacoraQuery,
  esquemaBitacoraPagina,
  type AccionBitacoraClave,
  type BitacoraSalida,
  type BitacoraQuery,
  type BitacoraPagina,
} from './esquemas/bitacora.js';

// ── Resumen operativo de la portada (rediseño R9, proto vResumen) ──
export {
  esquemaResumenOperativo,
  type ResumenOperativo,
  type OrdenPorVencer,
  type CorteSemanaResumen,
} from './esquemas/resumen.js';

export { esquemaSesionActual, type SesionActual } from './esquemas/sesion.js';

export { esquemaErrorApi, type ErrorApi } from './esquemas/error.js';

// ── Archivo histórico de órdenes del sistema viejo (§Post-F9.26, solo lectura) ────────────────────
export {
  PROCESOS_HISTORICOS,
  esquemaHistoricoOrdenesQuery,
  esquemaHistoricoOrdenResumen,
  esquemaHistoricoOrdenesPagina,
  esquemaHistoricoOrdenDetalle,
  type DatosHistoricoOrdenesQuery,
  type HistoricoOrdenResumen,
  type HistoricoOrdenesPagina,
  type HistoricoOrdenDetalle,
} from './esquemas/historico-ordenes.js';

// ── Directorio histórico de terceros del sistema viejo (§Post-F9.28, solo lectura) ────────────────
export {
  esquemaDirectorioTercerosQuery,
  esquemaDirectorioTercero,
  esquemaDirectorioTercerosPagina,
  type DatosDirectorioTercerosQuery,
  type DirectorioTercero,
  type DirectorioTercerosPagina,
} from './esquemas/directorio-terceros.js';
