/**
 * Contrato — lo compartido entre front y back (plan maestro §3): catálogo
 * tipado de permisos (A4) y esquemas Zod de entrada (una sola definición de
 * reglas de captura para UI y servidor). Es la fuente del OpenAPI que se genera
 * en E3 y desde el que el frontend deriva su cliente tipado.
 */
export {
  CATALOGO_PERMISOS,
  CLAVES_PERMISO,
  MODULOS_PERMISO,
  esClavePermiso,
  permisosPorModulo,
  type ClavePermiso,
  type DefinicionPermiso,
  type ModuloPermiso,
  type OrigenAcceso,
} from './permisos.js';

export { esquemaLogin, type DatosLogin } from './esquemas/login.js';

export {
  ETIQUETAS_TIPO_ALMACEN,
  TIPOS_ALMACEN,
  esquemaAlmacenCrear,
  esquemaAlmacenEditar,
  esquemaAlmacenSalida,
  esquemaAlmacenesQuery,
  esquemaAlmacenesPagina,
  type DatosAlmacenCrear,
  type DatosAlmacenEditar,
  type AlmacenSalida,
  type AlmacenesQuery,
  type AlmacenesPagina,
  type TipoAlmacenClave,
} from './esquemas/almacen.js';

export {
  esquemaUsuarioCrear,
  esquemaUsuarioEditar,
  esquemaUsuarioAsignarRoles,
  esquemaUsuarioCambiarContrasena,
  esquemaUsuarioSalida,
  esquemaUsuariosQuery,
  esquemaUsuariosPagina,
  type DatosUsuarioCrear,
  type DatosUsuarioEditar,
  type DatosUsuarioAsignarRoles,
  type DatosUsuarioCambiarContrasena,
  type UsuarioSalida,
  type UsuariosQuery,
  type UsuariosPagina,
} from './esquemas/usuario.js';

export {
  esquemaEmpresaCrear,
  esquemaEmpresaEditar,
  esquemaEmpresaSalida,
  esquemaConfiguracionEmpresaActualizar,
  esquemaConfiguracionEmpresaSalida,
  type DatosEmpresaCrear,
  type DatosEmpresaEditar,
  type EmpresaSalida,
  type DatosConfiguracionEmpresaActualizar,
  type ConfiguracionEmpresaSalida,
} from './esquemas/empresa.js';

export { esquemaRolSalida, type RolSalida } from './esquemas/rol.js';

// ── Catálogos (F1-E1): maestros globales (ADR-0007) ──────────────────────────
export {
  TIPOS_PROVEEDOR,
  ETIQUETAS_TIPO_PROVEEDOR,
  TIPOS_ARCHIVO_PROVEEDOR,
  ETIQUETAS_TIPO_ARCHIVO_PROVEEDOR,
  esquemaProveedorCrear,
  esquemaProveedorEditar,
  esquemaProveedorPatchCuerpo,
  esquemaProveedorSalida,
  esquemaProveedoresQuery,
  esquemaProveedoresPagina,
  esquemaRolProveedorSalida,
  esquemaProveedorAdjuntoCrear,
  esquemaProveedorAdjuntoSubida,
  esquemaProveedorAdjuntoSalida,
  esquemaProveedorAdjuntosLista,
  type DatosProveedorCrear,
  type DatosProveedorEditar,
  type DatosProveedorPatchCuerpo,
  type ProveedorSalida,
  type ProveedoresQuery,
  type ProveedoresPagina,
  type TipoProveedorClave,
  type TipoArchivoProveedorClave,
  type RolProveedorSalida,
  type DatosProveedorAdjuntoCrear,
  type ProveedorAdjuntoSubida,
  type ProveedorAdjuntoSalida,
  type ProveedorAdjuntosLista,
} from './esquemas/proveedor.js';

export {
  MONEDAS,
  METODOS_PAGO,
  esRfcValido,
  esClabeValida,
  type Moneda,
  type MetodoPago,
} from './esquemas/fiscal.js';

export {
  esquemaTemporadaCrear,
  esquemaTemporadaEditar,
  esquemaTemporadaSalida,
  esquemaTemporadasQuery,
  esquemaTemporadasPagina,
  type DatosTemporadaCrear,
  type DatosTemporadaEditar,
  type TemporadaSalida,
  type TemporadasQuery,
  type TemporadasPagina,
} from './esquemas/temporada.js';

export {
  esquemaEtiquetaMarcaCrear,
  esquemaEtiquetaMarcaEditar,
  esquemaEtiquetaMarcaSalida,
  esquemaEtiquetasMarcaQuery,
  esquemaEtiquetasMarcaPagina,
  type DatosEtiquetaMarcaCrear,
  type DatosEtiquetaMarcaEditar,
  type EtiquetaMarcaSalida,
  type EtiquetasMarcaQuery,
  type EtiquetasMarcaPagina,
} from './esquemas/etiqueta-marca.js';

export {
  esquemaColorCrear,
  esquemaColorEditar,
  esquemaColorSalida,
  esquemaColoresQuery,
  esquemaColoresPagina,
  esquemaColorFusionar,
  type DatosColorCrear,
  type DatosColorEditar,
  type ColorSalida,
  type ColoresQuery,
  type ColoresPagina,
  type DatosColorFusionar,
} from './esquemas/color.js';

// ── Catálogos estructurados (F1-E2): maestros globales con relaciones (ADR-0007) ──
// NOTA (fusión de terceros, D12/R15): maquileros se eliminó como catálogo (un maquilero
// es ahora un Proveedor con sus roles de servicio).
export {
  esquemaTallaCrear,
  esquemaTallaEditar,
  esquemaTallaSalida,
  esquemaListarTallas,
  esquemaTallasPagina,
  esquemaCurvaCrear,
  esquemaCurvaEditar,
  esquemaCurvaSalida,
  esquemaCurvaTallaItemSalida,
  esquemaListarCurvas,
  esquemaCurvasPagina,
  type DatosTallaCrear,
  type DatosTallaEditar,
  type TallaSalida,
  type ListarTallas,
  type TallasPagina,
  type DatosCurvaCrear,
  type DatosCurvaEditar,
  type CurvaSalida,
  type CurvaTallaItemSalida,
  type ListarCurvas,
  type CurvasPagina,
} from './esquemas/talla.js';

export {
  TIPOS_CAMPO_CLIENTE,
  esquemaClienteCrear,
  esquemaClienteEditar,
  esquemaClienteSalida,
  esquemaListarClientes,
  esquemaClientesPagina,
  esquemaClienteCampoCrear,
  esquemaClienteCampoEditar,
  esquemaClienteCampoSalida,
  type TipoCampoClienteClave,
  type DatosClienteCrear,
  type DatosClienteEditar,
  type ClienteSalida,
  type ListarClientes,
  type ClientesPagina,
  type DatosClienteCampoCrear,
  type DatosClienteCampoEditar,
  type ClienteCampoSalida,
} from './esquemas/cliente.js';

// ── Catálogos de materiales (F1-E3): globales con relaciones (ADR-0007/ADR-0009) ──
export {
  TIPOS_COMPONENTE_TELA,
  esquemaTelaCrear,
  esquemaTelaEditar,
  esquemaTelaSalida,
  esquemaListarTelas,
  esquemaTelasPagina,
  esquemaTelaColorSalida,
  esquemaTelaColoresLista,
  esquemaTelaCategoriaCrear,
  esquemaTelaCategoriaEditar,
  esquemaTelaCategoriaSalida,
  esquemaTelasCategoriasQuery,
  esquemaTelasCategoriasPagina,
  type TipoComponenteTelaClave,
  type DatosTelaCrear,
  type DatosTelaEditar,
  type TelaSalida,
  type ListarTelas,
  type TelasPagina,
  type TelaColorSalida,
  type TelaColoresLista,
  type DatosTelaCategoriaCrear,
  type DatosTelaCategoriaEditar,
  type TelaCategoriaSalida,
  type TelasCategoriasQuery,
  type TelasCategoriasPagina,
} from './esquemas/tela.js';

export {
  esquemaAvioCrear,
  esquemaAvioEditar,
  esquemaAvioPatchCuerpo,
  esquemaAvioSalida,
  esquemaListarAvios,
  esquemaAviosPagina,
  esquemaAvioProveedorSalida,
  esquemaAvioProveedoresLista,
  type DatosAvioCrear,
  type DatosAvioEditar,
  type DatosAvioPatchCuerpo,
  type AvioSalida,
  type ListarAvios,
  type AviosPagina,
  type AvioProveedorSalida,
  type AvioProveedoresLista,
} from './esquemas/avio.js';

export {
  TIPOS_BORDADO,
  ETIQUETAS_TIPO_BORDADO,
  esquemaBordadoCrear,
  esquemaBordadoEditar,
  esquemaBordadoPatchCuerpo,
  esquemaBordadoSalida,
  esquemaBordadosQuery,
  esquemaBordadosPagina,
  esquemaBordadoFotoCrear,
  esquemaBordadoFotoSubida,
  esquemaBordadoFotoSalida,
  type TipoBordadoClave,
  type DatosBordadoCrear,
  type DatosBordadoEditar,
  type DatosBordadoPatchCuerpo,
  type BordadoSalida,
  type BordadosQuery,
  type BordadosPagina,
  type DatosBordadoFotoCrear,
  type BordadoFotoSubida,
  type BordadoFotoSalida,
} from './esquemas/bordado.js';

// ── Modelos (Módulo 2, F1-E4): catálogo + receta/BOM + fotos (ADR-0007) ──────
export {
  TIPOS_FOTO_MODELO,
  ETIQUETAS_TIPO_FOTO_MODELO,
  esquemaGeneroSalida,
  esquemaModeloCrear,
  esquemaModeloEditar,
  esquemaModeloPatchCuerpo,
  esquemaModeloSalida,
  esquemaModeloFichaSalida,
  esquemaModelosQuery,
  esquemaModelosPagina,
  esquemaModeloTelaEntrada,
  esquemaModeloAvioEntrada,
  esquemaModeloBordadoEntrada,
  esquemaModeloTelaSalida,
  esquemaModeloAvioSalida,
  esquemaModeloBordadoSalida,
  esquemaModeloBomTelasCuerpo,
  esquemaModeloBomAviosCuerpo,
  esquemaModeloBomBordadosCuerpo,
  esquemaModeloBomTelasLista,
  esquemaModeloBomAviosLista,
  esquemaModeloBomBordadosLista,
  esquemaModeloCopiarBomCuerpo,
  esquemaModeloFotoCrear,
  esquemaModeloFotoSubida,
  esquemaModeloFotoSalida,
  esquemaModeloFotosLista,
  esquemaModeloFotoEditarCuerpo,
  type TipoFotoModeloClave,
  type GeneroSalida,
  type DatosModeloCrear,
  type DatosModeloEditar,
  type DatosModeloPatchCuerpo,
  type ModeloSalida,
  type ModeloFichaSalida,
  type ModelosQuery,
  type ModelosPagina,
  type DatosModeloTelaEntrada,
  type DatosModeloAvioEntrada,
  type DatosModeloBordadoEntrada,
  type DatosModeloBomTelas,
  type DatosModeloBomAvios,
  type DatosModeloBomBordados,
  type ModeloBomTelasLista,
  type ModeloBomAviosLista,
  type ModeloBomBordadosLista,
  type DatosModeloCopiarBom,
  type DatosModeloFotoCrear,
  type ModeloFotoSubida,
  type ModeloFotoSalida,
  type ModeloFotosLista,
  type DatosModeloFotoEditar,
} from './esquemas/modelo.js';

// ── Pedidos (Módulo PEDIDOS, F2-E1): pedido interno + pedido real (doc 02-Pedidos) ──
export {
  esquemaPedidoLineaEntrada,
  esquemaPedidoCrear,
  esquemaPedidoEditar,
  esquemaPedidoPatchCuerpo,
  esquemaPedidoCopiarCuerpo,
  esquemaPedidoLineaSalida,
  esquemaPedidoSalida,
  esquemaListarPedidos,
  esquemaPedidosPagina,
  esquemaPedidoRealCrear,
  esquemaPedidoRealEditar,
  esquemaPedidoRealLineaSeguimiento,
  esquemaPedidoRealSeguimientoCuerpo,
  esquemaPedidoRealLineaSalida,
  esquemaPedidoRealSalida,
  esquemaPedidoRealesLista,
  type DatosPedidoLineaEntrada,
  type DatosPedidoCrear,
  type DatosPedidoEditar,
  type DatosPedidoPatchCuerpo,
  type DatosPedidoCopiar,
  type PedidoLineaSalida,
  type PedidoSalida,
  type ListarPedidos,
  type PedidosPagina,
  type DatosPedidoRealCrear,
  type DatosPedidoRealEditar,
  type DatosPedidoRealLineaSeguimiento,
  type DatosPedidoRealSeguimiento,
  type PedidoRealLineaSalida,
  type PedidoRealSalida,
  type PedidoRealesLista,
} from './esquemas/pedido.js';

// ── Órdenes de producción (Módulo ÓRDENES, F2-E2; doc 03-Produccion) ──────────
export {
  esquemaOrdenTallaEntrada,
  esquemaOrdenLineaEntrada,
  esquemaOrdenCrear,
  esquemaOrdenEditar,
  esquemaOrdenPatchCuerpo,
  esquemaOrdenMatrizCuerpo,
  esquemaOrdenCopiarMatrizCuerpo,
  esquemaOrdenCancelarCuerpo,
  esquemaOrdenReferenciaEntrada,
  esquemaOrdenReferenciasCuerpo,
  esquemaOrdenComentarioCuerpo,
  esquemaEstadoOrden,
  esquemaOrdenTallaSalida,
  esquemaOrdenLineaSalida,
  esquemaOrdenReferenciaSalida,
  esquemaOrdenComentarioSalida,
  esquemaOrdenSalida,
  esquemaListarOrdenes,
  esquemaOrdenesPagina,
  esquemaOrdenesImpresoCuerpo,
  type DatosOrdenTallaEntrada,
  type DatosOrdenLineaEntrada,
  type DatosOrdenCrear,
  type DatosOrdenEditar,
  type DatosOrdenPatchCuerpo,
  type DatosOrdenMatriz,
  type DatosOrdenCopiarMatriz,
  type DatosOrdenCancelar,
  type DatosOrdenReferenciaEntrada,
  type DatosOrdenReferencias,
  type DatosOrdenComentario,
  type OrdenTallaSalida,
  type OrdenLineaSalida,
  type OrdenReferenciaSalida,
  type OrdenComentarioSalida,
  type OrdenSalida,
  type ListarOrdenes,
  type OrdenesPagina,
  type DatosOrdenesImpreso,
} from './esquemas/orden.js';

// ── Consultas/tableros/búsqueda de Órdenes (Módulo ÓRDENES, F2-E4; doc 03-Produccion) ──
export {
  esquemaOrdenLigeraSalida,
  esquemaOrdenesLigerasPagina,
  esquemaConsultaOrdenes,
  esquemaSemaforoOrden,
  esquemaOrdenIncompletaSalida,
  esquemaOrdenesIncompletasPagina,
  esquemaIncompletasQuery,
  esquemaTableroPedidosMesFila,
  esquemaTableroPedidosMes,
  esquemaTableroPedidosMesQuery,
  esquemaOrdenHitSalida,
  esquemaOrdenesBuscarSalida,
  esquemaOrdenesBuscarQuery,
  type OrdenLigeraSalida,
  type OrdenesLigerasPagina,
  type ConsultaOrdenes,
  type SemaforoOrden,
  type OrdenIncompletaSalida,
  type OrdenesIncompletasPagina,
  type IncompletasQuery,
  type TableroPedidosMesFila,
  type TableroPedidosMes,
  type TableroPedidosMesQuery,
  type OrdenHitSalida,
  type OrdenesBuscarSalida,
  type OrdenesBuscarQuery,
} from './esquemas/orden-consulta.js';

// ── Producción / WIP + kardex (Módulo 4/6, F3-E1; doc 03-Produccion / 04-Inventarios) ──
export {
  esquemaTipoProcesoCrear,
  esquemaTipoProcesoEditar,
  esquemaTipoProcesoSalida,
  esquemaTiposProcesoQuery,
  esquemaTiposProcesoPagina,
  type DatosTipoProcesoCrear,
  type DatosTipoProcesoEditar,
  type TipoProcesoSalida,
  type TiposProcesoQuery,
  type TiposProcesoPagina,
} from './esquemas/tipo-proceso.js';

export {
  DIRECCIONES_MOVIMIENTO,
  ETIQUETAS_DIRECCION_MOVIMIENTO,
  esquemaTipoMovimientoSalida,
  esquemaTiposMovimientoQuery,
  esquemaTiposMovimientoLista,
  type DireccionMovimientoClave,
  type TipoMovimientoSalida,
  type TiposMovimientoQuery,
  type TiposMovimientoLista,
} from './esquemas/tipo-movimiento.js';

// ── Inventario PT operable: movimientos, traspasos, existencias y kardex (F3-E3; doc 04-Inventarios) ──
export {
  esquemaMovimientoPtCrear,
  esquemaTraspasoPtCrear,
  esquemaMovimientoPtCancelarCuerpo,
  esquemaMovimientoPtSalida,
  esquemaTraspasoPtSalida,
  esquemaExistenciasPtQuery,
  esquemaExistenciasPtLista,
  esquemaKardexPtQuery,
  esquemaKardexPtLista,
  esquemaParamFolio,
  type DatosMovPtLineaEntrada,
  type DatosMovimientoPtCrear,
  type DatosTraspasoPtCrear,
  type DatosMovimientoPtCancelar,
  type MovimientoPtSalida,
  type TraspasoPtSalida,
  type ExistenciasPtQuery,
  type ExistenciaPtFila,
  type ExistenciasPtLista,
  type KardexPtQuery,
  type KardexPtRenglon,
  type KardexPtLista,
} from './esquemas/movimiento-pt.js';

// ── Etapas de producción: corte + envío a maquila (F3-E2; doc 03-Produccion) ──
export {
  esquemaCorteCrear,
  esquemaEnvioCrear,
  esquemaEtapaCancelarCuerpo,
  esquemaEtapaSalida,
  esquemaEtapasOrdenLista,
  esquemaPendientesOrden,
  esquemaCorteSemanalQuery,
  esquemaCorteSemanalLista,
  type DatosCorteCrear,
  type DatosEnvioCrear,
  type DatosEtapaCancelar,
  type DatosEtapaLineaEntrada,
  type EtapaSalida,
  type EtapasOrdenLista,
  type PendientesOrden,
  type CorteSemanalQuery,
  type CorteSemanalLista,
} from './esquemas/etapa.js';

// ── Recibo de maquila (F3-E4; doc 03-Produccion Paso 5) ──────────────────────
export {
  esquemaReciboCrear,
  esquemaReciboCancelarCuerpo,
  esquemaReciboSalida,
  esquemaPendientesRecibir,
  esquemaRecibosSemanalesQuery,
  esquemaRecibosSemanalesLista,
  type DatosReciboLineaEntrada,
  type DatosReciboCrear,
  type DatosReciboCancelar,
  type ReciboSalida,
  type PendientesRecibir,
  type RecibosSemanalesQuery,
  type RecibosSemanalesLista,
} from './esquemas/recibo.js';

// ── Cargos EsMa: cola de validación derivada de los recibos (F3-E4; doc 07-EsMa) ──
export {
  esquemaCargoEsMaValidarCuerpo,
  esquemaCargosEsMaQuery,
  esquemaCargoEsMaSalida,
  esquemaCargosEsMaLista,
  type DatosCargoEsMaValidar,
  type CargosEsMaQuery,
  type CargoEsMaSalida,
  type CargosEsMaLista,
} from './esquemas/esma.js';

export { esquemaSesionActual, type SesionActual } from './esquemas/sesion.js';

export { esquemaErrorApi, type ErrorApi } from './esquemas/error.js';
